### PR TITLE
add RIO from Realio

### PR DESCRIPTION
**Pull request by hoangdv2429**
## Description

Adding chain: Realio
Adding token: ario or RIO
Pool Id: 1179

### Adding Chains

If adding a new chain, please ensure the following:
- [x] Chain is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).

  Note:
   - Chain's registration must have `staking` defined, with at least one `staking_token` denom specified.
   - Chain's registration must have `fees` defined; at least one fee token has low, average, and high gas prices defined.
- [x] Add chain to bottom of `zone_chains.json`

  Note:
   - RPC and REST must not have any CORS blocking of the Osmosis domain.
   - RCP node must have WSS enabled.

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
- [x] Add asset to bottom of `zone_assets.json`.

  Note:
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_main` defaults to `false` (or else cite the listing rule that justifies enlisting to the Main app)

### On-chain liquidity

If adding a new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [ ] The submitting team will ensure a pool will be created soon. Please hold off until further communication, which will notify of the Pool ID. (Please set the PR's status to Draft until the pool has been created)

OR
- [ ] A preview link is requested for the submitting team to be able to create a pool using the Osmosis Frontend.

OR
- [x] The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

### Validation Testing

If adding or updating a chain or asset, the changes must be validated from the updated build of the Osmosis Frontend. Testers will need a small amount of tokens to validate. 
  - [x] Validaters can buy a small amount of this asset from Pool ID: 1179.
  - [x] Preview build has been validated.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Everything seems to otherwise be in order except to Deposit function, which doesn't work for eth-signed assets from Osmosis' frontend natively, so we need another frontend interface that users can use to Deposit. Do we have one @hoangdv2429 ?

**Comment by hoangdv2429** [comment]
@JeremyParish69 yes we have, I just don't know where to put it in sir. Here is the link https://app.realio.network/

**Comment by hoangdv2429** [comment]
@JeremyParish69 hi sir, can you help me with this PR. I really want to make this work asap. Sorry  if I disturb you. Thank you!

**Comment by JeremyParish69** [comment]
@hoangdv2429 There is no issue with this PR--it is just awaiting merging of a corresponding PR on our Frontend repo, which has almost passed validation, but there is an issue that needs to be resolved first. This should be added within the coming days.

**Comment by jiujiteiro** [comment]
@JeremyParish69 I know you guys are cranking! Which PR are we waiting on is it https://github.com/osmosis-labs/osmosis-frontend/pull/2206?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 I know you guys are cranking! Which PR are we waiting on is it [osmosis-labs/osmosis-frontend#2206](https://github.com/osmosis-labs/osmosis-frontend/pull/2206)?

 Yes, but were are completely blocked on all listings until we can restore transfer functionality in the frontend staging environment. Once that's fixed, these pending listings will be top priority.

**Pull request merged**
