### PR TITLE
Add lambda to frontier

### PR DESCRIPTION
**Pull request by steveliupai**
1.  Add lambda to frontier
2. Use prettier to pretty the json file

### CODE REVIEW

**Comment by steveliupai** [comment]
@IbrarMakaveli Hi, please review and merge, thank you so much

**Comment by steveliupai** [comment]
@JeremyParish69 Hi please merge, thank you

**Comment by JeremyParish69** [comment]
Thanks @steveliupai , Although in my experience, dumping a serialized json via script seems to always create a new line for values enclosed in braces '[]', there are also some other formatting fixes, which are of benefit, so I'm inclined to accept those changes. However, the addition of new tokens to this assetlists repo usually takes place after first adding the token to the Osmosis Frontend repo in here: https://github.com/osmosis-labs/osmosis-frontend/tree/master/packages/web/config . Are there plans to add the token to the Osmosis Frontend?

**Comment by steveliupai** [comment]
> Thanks @steveliupai , Although in my experience, dumping a serialized json via script seems to always create a new line for values enclosed in braces '[]', there are also some other formatting fixes, which are of benefit, so I'm inclined to accept those changes. However, the addition of new tokens to this assetlists repo usually takes place after first adding the token to the Osmosis Frontend repo in here: https://github.com/osmosis-labs/osmosis-frontend/tree/master/packages/web/config . Are there plans to add the token to the Osmosis Frontend?

@JeremyParish69 Thank you for replying. We are planning to add the token to both Frontier and Frontend. Should i add lambda token to Frontend too? Pr hasn't been merged for a long time, cause i thought it should be merged to Frontier first then Frontend

**Pull request closed without merging**
