### PR TITLE
Frontier - add Evmos

### PR DESCRIPTION
**Pull request by doggystylez**
changes made per https://github.com/osmosis-labs/assetlists/pull/138
see: https://github.com/cosmos/chain-registry/pull/378
replaced logo with new red one

### CODE REVIEW

**Comment by doggystylez** [comment]
EVMOS/OSMO pool: https://frontier.osmosis.zone/pool/722

**Comment by fedekunze** [comment]
cc @JeremyParish69

**Comment by doggystylez** [comment]
Pool 722 now has sufficient liquidity

**Comment by sunnya97** [comment]
@doggystylez can you make a PR to add it to main assetlist too (not frontier)

**Pull request merged**
