### PR TITLE
Fix FURY Channel-id

### PR DESCRIPTION
**Pull request by JeremyParish69**
## Description

Fix FURY Channel-id
since it was updated

### CODE REVIEW

**Comment by sudopunk** [comment]
This doesn't seem like it has taken effect on the frontend.

**Comment by JeremyParish69** [comment]
Apologies, we had a temporary update freeze on the frontend app, but the backend details are correct and will be updated shortly

**Comment by sudopunk** [comment]
Now the error has changed to this:

`Fetch error. JSON parse error: SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON.
`

**Comment by JeremyParish69** [comment]
> Now the error has changed to this:
> 
> `Fetch error. JSON parse error: SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON. `

It might've been temporary. It worked fine for me

**Comment by sudopunk** [comment]
> > Now the error has changed to this:
> > 
> > `Fetch error. JSON parse error: SyntaxError: Unexpected token '<', "<html> <h"... is not valid JSON. `
> 
> It might've been temporary. It worked fine for me

This issue still exists. Should I open an issue for this?

**Comment by JeremyParish69** [comment]
> 
> This issue still persists. Should I open an issue for this?


I'm unable to obtain FURY on Osmosis, so I'm not able to check myself (not sure how I had it working before).

Can I ask which query returns that invlaid json message?

**Comment by sudopunk** [comment]
image

This happens when I try to deposit FURY into the Osmosis chain, via the deposit button in the Portfolio page of the app.

**Comment by JeremyParish69** [comment]
Hmm there's likely issues with the nodes, then. Could we try looking at different nodes?
Current nodes:
https://github.com/osmosis-labs/assetlists/blob/6ebe297fce63f16825d820b76d794fa21950b74d/osmosis-1/osmosis.zone_chains.json#L1223-L1224

**Pull request merged**
