### PR TITLE
Add IBC (ImBeCiles) to Osmosis Assets

### PR DESCRIPTION
**Pull request by imbecile-dev**
## Description

Adding token: IBC from chain Osmosis

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - The `description` and/or `extended_description` of the asset in the Chain Registry is informative.
- [x] Add asset to bottom of `zone_assets.json`.
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_unlisted` defaults to `true` (until the respesentation and transferring of the new asset has been validated)
   - Note that it is recommended to include an X (fka, Twitter) profile URL with each asset.

### On-chain liquidity

For each new asset, please provide the plan for on-chain liquidity of the asset (See: [Pool Setup Guilde](https://docs.osmosis.zone/overview/integrate/pool-setup).): (choose one)
- [ ] Ready -- A liquidity pool(s) has been created and has liquidity. The pool ID is: ______
- [x] Soon -- A pool will be created soon. Do not merge this PR until liquidity is ready. 
  - [x] (optional) A preview of the Osmosis Zone app with the new asset added is requested for creating the pool. (Note: This method is not recommended because the Supercharged Liquidity pool type cannot be created via the Osmosis Zone app)
- [ ] StreamSwap -- The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds. The StreamSwap Bootstrapping phase begins (when?): ______

### CODE REVIEW

**Comment by imbecile-dev** [comment]
Whats this _comment param for and what exactly do I do to add for the same for my token?

image

**Comment by JeremyParish69** [comment]
> Whats this _comment param for and what exactly do I do to add for the same for my token?
> 
> image

It had no function, just an indicator to readers of that document which coin it is. Makes for easier searching is all.

**Comment by JeremyParish69** [comment]
By policy, we don't allowing registrations from brand new GitHub accounts. Is there a github account with a longer history that can comment on this thread?
https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#listing-as-an-unverified-asset-pseudo-permissionless

**Comment by sunnya97** [comment]
giving my ack to the merging of this

**Comment by JeremyParish69** [comment]
Is there plan to create a pool of this?
A preview can be seen here: https://app.osmosis.zone/assets?show_preview_assets=true

**Comment by imbecile-dev** [comment]
@JeremyParish69 I dont see the asset on this yet: https://app.osmosis.zone/assets?show_preview_assets=true, pls lmk how I can rectify

And yes we are going to be making a pool for this soon

**Comment by JeremyParish69** [comment]
When I search for IBC on the assets page, it shows up for me
image

**Pull request merged**
