### PR TITLE
add KLEO token

### PR DESCRIPTION
**Pull request by Jazz877**
## Description

Add KLEO from Juno

## Checklist

  Note:
   - RPC and REST must not have any CORS blocking of the Osmosis domain.
   - RCP node must have WSS enabled.

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
- [x] Add asset to bottom of `zone_assets.json`.

  Note:
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_main` defaults to `false` (or else cite the listing rule that justifies enlisting to the Main app)

### On-chain liquidity

- [x] A preview link is requested for the submitting team to be able to create a pool using the Osmosis Frontend.

### Validation Testing

If adding or updating a chain or asset, the changes must be validated from the updated build of the Osmosis Frontend. Testers will need a small amount of tokens to validate. 
  - [ ] Validaters can buy a small amount of this asset from Pool ID: {PROVIDE POOL ID}.
  - [ ] Preview build has been validated.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please specify the ID of the Osmosis pool containing KLEO

**Comment by Jazz877** [comment]
> Please specify the ID of the Osmosis pool containing KLEO

Hi @JeremyParish69, sorry but I forgot to select one option for the `On-chain liquidity` step, I've just updated the comment now. We are going to need a preview link in order to create the new liquidity pool on the Osmosis Frontend.

**Comment by JeremyParish69** [comment]
Here is a preview link you can use to create the pool using the Frontend:
https://osmosis-frontend-git-jp69-asset-kleo-add-osmo-labs.vercel.app/

**Comment by JeremyParish69** [comment]
Any update on this?

**Comment by JeremyParish69** [comment]
Looks abandoned

**Comment by Jazz877** [comment]
@JeremyParish69 sorry I didn't read your previous messages. We couldn't move our liquidity before. Can we reopen this PR and proceed please?

**Comment by JeremyParish69** [comment]
Yes, we can reopen it @Jazz877 . Please let me know the ID of the liquidity pool

**Comment by Jazz877** [comment]
Thank you @JeremyParish69

**Comment by Jazz877** [comment]
@JeremyParish69 we created the pool: ID 1352

**Comment by Trigs-0** [comment]
Let me know if you need some KLEO for testing, @JeremyParish69

**Comment by Trigs-0** [comment]
Maybe you can help me understand this:

I added 8000USDC and 10416666KLEO to the pool, a 50/50 stableswap pool. Shouldn't that have set the price at $0.000768?

When I look on the swap interface it looks like the price is $0.002064. It was higher before but I sold 290,531 more KLEO into the pool (as I had that much leftover still from migrating our LP from Juno) just to bring it down a little.

**Comment by Trigs-0** [comment]
OK we figured it out. We screwed up and made a stableswap pool.

So we pulled the liquidity and made a new pool, weighted 50/50 like it should be.

so it's pool #1353 now!

can we get pool 1352 closed and the remainder of the balance returned? I couldn't drain it fully. Guessing the pool creation fee is sunk, but that's ok it was our mistake.

**Comment by JeremyParish69** [comment]
> OK we figured it out @JeremyParish69. We screwed up and made a stableswap pool.
> 
> So we pulled the liquidity and made a new pool, weighted 50/50 like it should be.
> 
> so it's pool #1353 now!
> 
> can we get pool 1352 closed and the remainder of the balance returned? I couldn't drain it fully. Guessing the pool creation fee is sunk, but that's ok it was our mistake.

good to note the current pool.

There is no way to completely close a pool, it would just sit dormant if there is no liquidity in it. If you were unable to withdraw all the liquidity, then I'm thinking there must be other LPs who own a little bit of it. Or maybe I'm not understanding why the liquidity couldn't be withdrawn from it.

**Comment by Trigs-0** [comment]
> > OK we figured it out @JeremyParish69. We screwed up and made a stableswap pool.
> > So we pulled the liquidity and made a new pool, weighted 50/50 like it should be.
> > so it's pool #1353 now!
> > can we get pool 1352 closed and the remainder of the balance returned? I couldn't drain it fully. Guessing the pool creation fee is sunk, but that's ok it was our mistake.
> 
> good to note the current pool.
> 
> There is no way to completely close a pool, it would just sit dormant if there is no liquidity in it. If you were unable to withdraw all the liquidity, then I'm thinking there must be other LPs who own a little bit of it. Or maybe I'm not understanding why the liquidity couldn't be withdrawn from it.

It provides this error when I use 'max withdraw':

`Trying to exit >= the number of shares contained in the pool.: invalid calculated result [osmosis-labs/osmosis/v21/x/gamm/keeper/pool_service.go:329] With gas wanted: '120000000' and gas used: '311157' (at msg 0)`

But when I back it off a tic I can keep gradually withdrawing more, so I was able to get it virtually empty by leaving some dust in it.

**Comment by Trigs-0** [comment]
@JeremyParish69 is there anything else we need to do on our end to get $KLEO listed on the live production front end? Not trying to rush, just wanting to make sure we have everything in order.

Wasn't able to get the answers needed from the docs, not sure if we weren't looking in the right spot or if they're being updated atm.

**Pull request merged**
