### PR TITLE
added `qOSMO` as an asset

### PR DESCRIPTION
**Pull request by ajansari95**
- `qOSMO` IBCDenom on osmosis ` ibc/42D24879D4569CE6477B7E88206ADBFE47C222C6CAD51A54083E4A72594269FC`

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Do you have a pool id for qOSMO? If not, is a staging link required to to create one?

**Comment by JeremyParish69** [comment]
You may use this staging link to create a pool.
https://osmosis-frontier-git-jp69-add-qosmo-osmo-labs.vercel.app/

**Comment by joe-bowman** [comment]
@JeremyParish69 - pool id is 956

**Comment by JeremyParish69** [comment]
Thanks for confirming. Could you please add to the osmosis.zone.json file?

**Comment by ajansari95** [comment]
@JeremyParish69 have added to `osmosis.zone.json` file

**Pull request merged**
