### PR TITLE
Add NEXX to Osmo-test-5/osmosis.zone_assets

### PR DESCRIPTION
**Pull request by NEXXGENAI**
Add NEXX to Osmo-test-5/osmosis.zone_assets
All other changes do not require review at this time

### CODE REVIEW

**Comment by JeremyParish69** [comment]
The data entered is mostly incorrect. Please delete all your changes except for those on /osmo-test-5/osmosis.zone_assets.json

**Comment by NEXXGENAI** [comment]
> The data entered is mostly incorrect. Please delete all your changes except for those on /osmo-test-5/osmosis.zone_assets.json

Files changed and additions removed except for osmo-test-5/osmosis.zone_assets.json

**Comment by JeremyParish69** [comment]
The juno testnet contract ibc connection to osmosis testnet needs to be registered to the chain registry

**Comment by NEXXGENAI** [comment]
> The juno testnet contract ibc connection to osmosis testnet needs to be registered to the chain registry

Which file in the chain registry should the IBC connection be added to?
Thanks

**Comment by JeremyParish69** [comment]
> > The juno testnet contract ibc connection to osmosis testnet needs to be registered to the chain registry
> 
> Which file in the chain registry should the IBC connection be added to? Thanks

To this one under /testnets/: https://github.com/cosmos/chain-registry/blob/master/testnets/_IBC/junotestnet-osmosistestnet.json
and it might look similar to the [mainnet example](https://github.com/cosmos/chain-registry/blob/master/_IBC/juno-osmosis.json)

**Comment by JeremyParish69** [comment]
A Preview Frontend is building now. But I cannot validate without a small amount of Deposit and Withdraw. Is there any pool set up where I can buy some?

**Comment by NEXXGENAI** [comment]
> A Preview Frontend is building now. But I cannot validate without a small amount of Deposit and Withdraw. Is there any pool set up where I can buy some?



> A Preview Frontend is building now. But I cannot validate without a small amount of Deposit and Withdraw. Is there any pool set up where I can buy some?

Good morning, Jeremy.  We have not yet setup a pool on testnet, but we can today.  I noticed you added our testnet relayer to Github.  Just wanted to clarify, does this mean that we no longer need to seek goverance approval to re-open the original client as previously instructed?  

Thanks,
Paul

**Comment by JeremyParish69** [comment]
> Good morning, Jeremy. We have not yet setup a pool on testnet, but we can today. I noticed you added our testnet relayer to Github. Just wanted to clarify, does this mean that we no longer need to seek goverance approval to re-open the original client as previously instructed?
> 
> Thanks, Paul

Just following up, is there a pool now so we can finish validation?

**Comment by NEXXGENAI** [comment]
> > Good morning, Jeremy. We have not yet setup a pool on testnet, but we can today. I noticed you added our testnet relayer to Github. Just wanted to clarify, does this mean that we no longer need to seek goverance approval to re-open the original client as previously instructed?
> > Thanks, Paul
> 
> Just following up, is there a pool now so we can finish validation?

Will have this done early this week.  Thanks

**Comment by NEXXGENAI** [comment]
> > Good morning, Jeremy. We have not yet setup a pool on testnet, but we can today. I noticed you added our testnet relayer to Github. Just wanted to clarify, does this mean that we no longer need to seek goverance approval to re-open the original client as previously instructed?
> > 
> > Thanks, Paul
> 
> Just following up, is there a pool now so we can finish validation?
> 

Testnet pool for NEXX: https://testnet.osmosis.explorers.guru/transaction/195A97506182DFBC9A3C9186BE9FFF10B5E5494DF2CBF2522BCCCAD807799708

**Comment by JeremyParish69** [comment]
Sorry to leave this quite for so long. Looks like the ibc connection between Juno and Osmosis has since been replaced. Do we have a liquidity pool for this using the current ibc channels?

**Comment by JeremyParish69** [comment]
Can reopen or replace if necessary, but effort seems abandoned

**Pull request closed without merging**
