### PR TITLE
feat: Add SEDA asset and chain

### PR DESCRIPTION
**Pull request by hacheigriega**
## Description

This PR proposes registration the SEDA token for SEDA Chain on Osmosis.
We are planning to provide around 1mm of liquidity and set up a pool in near future.

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
- [x] Add asset to bottom of `zone_assets.json`.
   - [x] `chain_name` and `base_denom` are provided and use values exactly as defined at the Chain Registry.
   - [x] `path` is provided, and the IBC channel referenced is registered at the Chain Registry (unless native to Osmosis).
   - [x] `osmosis_verified` is set to `false`
   - [x] `listing_date_time_utc` is specified and accurate
   - [x] Optional: `transfer_methods`, `peg_mechanism`, `override_properties`, `canonical`, `categories`, where necessary (see [README](https://github.com/osmosis-labs/assetlists/tree/main?tab=readme-ov-file#how-to-add-assets) for details).

### Adding Chains

If adding a new chain, please ensure the following:
- [x] Chain is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - Chain's registration must have `staking` defined, with at least one `staking_token` denom specified.
   - Chain's registration must have `fees` defined; at least one fee token has low, average, and high gas prices defined.
- [x] IBC Connection between chain and Osmosis is registered.
- [x] Add chain to bottom of `zone_chains.json`
   - [x] `rpc` and `rest` does not have any CORS blocking of the Osmosis domain, and RPC node has have WSS enabled.
   - [x] `explorer_tx_url` correctly directs to the transaction when the hash is inserted into the URL.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can we keep the checklist for new chains and assets?

**Comment by JeremyParish69** [comment]
Also, seems like checks are failing because there is no osmosis-seda ibc connection registered at the Chain Registry https://github.com/cosmos/chain-registry/tree/master/_IBC

**Comment by hacheigriega** [comment]
Thanks for the prompt review. Submitted a PR for IBC connection https://github.com/cosmos/chain-registry/pull/4539

**Comment by hacheigriega** [comment]
Please note that the provided RPC node's WSS may not be working at the moment. We will try to fix it ASAP.

**Comment by JeremyParish69** [comment]
Did you want this the be hidden as a preview asset?

**Pull request merged**
