### PR TITLE
add brnch token

### PR DESCRIPTION
**Pull request by lakmalmabm**
Adding token: BRNCH from chain Stargaze

we are planning to add this token as the incentive token of the USC/STRDST pool. 
https://app.osmosis.zone/pool/1234

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Is there a pool with BRNCH in it? 1234 is STRDST/USDC, but doesn't contain BRNCH and therefore cannot be used to define it's value

**Comment by JeremyParish69** [comment]
> as for the details I got my client is,
> 
> "This is the only way it’s brought into circulation. That we will have a StreamSwap for it in the future. Also it wouldn’t be used to define any value. It’s simply the reward token we are giving for the pool"
> 
> @JeremyParish69 so basically it will be the incentive token for the pool https://app.osmosis.zone/pool/1234

Alright, thanks for the info. We'll be able to add it once someone creates a pool or once the StreamSwap takes place but for now it doesn't make sense to enlist a token that has no value and cannot be swapped. Users will still be able to receive the incentive.

**Comment by lakmalmabm** [comment]
thanks for the info @JeremyParish69 

so but it will not pick the token name and the logo, right?

**Comment by JeremyParish69** [comment]
> thanks for the info @JeremyParish69
> 
> so but it will not pick the token name and the logo, right?

Yes, that's right, it will not be shown.

**Comment by lakmalmabm** [comment]
Hi @JeremyParish69 we have added BRNCH token as the incentive token for the pool 1234. 

https://www.mintscan.io/osmosis/tx/C43588EBAFBB628D04216A1C5C0A1E6179942499F5D2CD27550A6C4CE0146595?height=12214760

But it is not showing the token name and token logo.

**Comment by JeremyParish69** [comment]
> Hi @JeremyParish69 we have added BRNCH token as the incentive token for the pool 1234.
> 
> https://www.mintscan.io/osmosis/tx/C43588EBAFBB628D04216A1C5C0A1E6179942499F5D2CD27550A6C4CE0146595?height=12214760
> 
> But it is not showing the token name and token logo.

Exciting. Once a pool is created, we should be able to proceed with the listing and then the frontend will have the data it needs to show this as a reward token and its APR.

**Comment by lakmalmabm** [comment]
Hi, @JeremyParish69 we have created the pool today. Please have a look. 

https://app.osmosis.zone/pool/1287

thank you.

**Comment by lakmalmabm** [comment]
Hi @JeremyParish69 please ignore the above pool. The correct pool id is https://app.osmosis.zone/pool/1288. 

thank you.

**Pull request merged**
