### PR TITLE
Image optimisations

### PR DESCRIPTION
**Pull request by ankurdotb**
## Lossless image optimisations to reduce file size

Your image file size has been reduced by **24%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /images/akt.png | 19.12kb | 6.29kb | 67.12% |
| /images/band.png | 431.28kb | 156.86kb | 63.63% |
| /images/iov.svg | 3.83kb | 1.64kb | 57.28% |
| /images/cro.png | 28.51kb | 12.85kb | 54.91% |
| /images/tick.png | 31.51kb | 14.66kb | 53.48% |
| /images/huahua.png | 36.10kb | 17.42kb | 51.75% |
| /images/xprt.png | 14.86kb | 7.50kb | 49.55% |
| /images/scrt.png | 18.21kb | 9.88kb | 45.70% |
| /images/lum.png | 77.80kb | 43.39kb | 44.23% |
| /images/med.png | 14.03kb | 8.49kb | 39.48% |
| /images/atom.png | 55.10kb | 34.07kb | 38.17% |
| /images/juno.svg | 15.91kb | 10.99kb | 30.96% |
| /images/ixo.png | 11.15kb | 7.91kb | 29.10% |
| /images/dvpn.png | 110.85kb | 79.68kb | 28.12% |
| /images/eeur.png | 31.95kb | 23.66kb | 25.93% |
| /images/bcna.png | 37.38kb | 28.99kb | 22.46% |
| /images/iov.png | 46.22kb | 35.93kb | 22.26% |
| /images/iris.png | 131.33kb | 102.31kb | 22.10% |
| /images/ion.png | 137.18kb | 107.56kb | 21.59% |
| /images/juno.png | 47.87kb | 38.25kb | 20.10% |
| /images/hash.png | 23.25kb | 18.61kb | 19.96% |
| /images/dsm.png | 329.18kb | 275.98kb | 16.16% |
| /images/tick.svg | 11.24kb | 9.45kb | 15.89% |
| /images/regen.png | 51.70kb | 44.05kb | 14.79% |
| /images/cmdx.png | 35.68kb | 30.47kb | 14.61% |
| /images/dig.png | 83.93kb | 72.64kb | 13.45% |
| /images/xki.png | 22.24kb | 19.27kb | 13.34% |
| /images/bcna.svg | 2.40kb | 2.10kb | 12.43% |
| /images/cheq.svg | 5.91kb | 5.19kb | 12.21% |
| /images/cheq.png | 31.24kb | 28.53kb | 8.65% |
| /images/band.svg | 1.70kb | 1.58kb | 6.68% |
| /images/stars.png | 96.90kb | 90.68kb | 6.42% |
| /images/hash.svg | 0.60kb | 0.57kb | 6.00% |
| /images/osmo.png | 222.16kb | 208.87kb | 5.98% |
| /images/like.svg | 5.51kb | 5.30kb | 3.90% |
| /images/btsg.png | 25.47kb | 24.87kb | 2.35% |
| /images/osmo.svg | 15.50kb | 15.25kb | 1.58% |
| /images/akt.svg | 0.34kb | 0.34kb | 1.42% |
| /images/somm.png | 294.65kb | 290.99kb | 1.24% |
| /images/ion.svg | 16.96kb | 16.76kb | 1.14% |
| /images/lum.svg | 20.69kb | 20.47kb | 1.09% |
| /images/krt.png | 139.17kb | 138.07kb | 0.79% |
| /images/dsm.svg | 4.63kb | 4.60kb | 0.72% |
| /images/rowan.svg | 3.55kb | 3.52kb | 0.69% |
| /images/btsg.svg | 2.60kb | 2.58kb | 0.56% |
| /images/luna.svg | 1.09kb | 1.09kb | 0.54% |
| /images/atom.svg | 3.86kb | 3.85kb | 0.28% |
| /images/scrt.svg | 2.85kb | 2.85kb | 0.27% |
| /images/ngm.svg | 0.73kb | 0.73kb | 0.13% |
| | | | |
| **Total :** | **2,755.90kb** | **2,087.56kb** | **24.25%** |
</details>

---

[📝 docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/imgbot/ImgBot) | [🙋🏾 issues](https://github.com/imgbot/ImgBot/issues) | [🏪 marketplace](https://github.com/marketplace/imgbot)

<i>~Imgbot - Part of [Optimole](https://optimole.com/) family</i>

### CODE REVIEW

**Comment by sunnya97** [comment]
@IbrarMakaveli do you think we should do this?

**Comment by IbrarMakaveli** [comment]
I think, it's good, it's the img bot that comes from the Cheq project :https://imgbot.net/

**Comment by IbrarMakaveli** [comment]
@ankurdotb I will close this one and can you create new one, since we have a lot of new img, tysm !

**Comment by ankurdotb** [comment]
Hey @IbrarMakaveli @sunnya97, do you want me to send a new PR, or set up Imgbot yourself? It's free for Github open source projects, and can be configured like this: https://imgbot.net/docs/#configuration

It will allow you to control the schedule it runs on, as well as other parameters. We've got it configured to _only_ do lossless optimisations, and the smaller filesizes of course are better for faster loading, SEO rankings etc. 

Happy to do a PR and send instead if you'd rather not spend the time setting it up.

**Comment by sunnya97** [comment]
Hey @ankurdotb sure, that would be great!  Hopefully it can help some of the pages load faster :)

Thanks!

**Comment by ankurdotb** [comment]
> Hey @ankurdotb sure, that would be great! Hopefully it can help some of the pages load faster :)
> 
> Thanks!

Cool! Created a new PR here with latest upstream changes: https://github.com/osmosis-labs/assetlists/pull/125

**Pull request closed without merging**
