### PR TITLE
Frontier - Add Racoon CW20 

### PR DESCRIPTION
**Pull request by racoon-supply-rac**
Add Racoon CW20 Token to Asset list

### CODE REVIEW

**Comment by racoon-supply-rac** [comment]
Hi @IbrarMakaveli do we need anything else for this PR to be merged? Thanks very much

**Comment by JeremyParish69** [comment]
Can we please rename racoon.svg and racoon.png to rac.svg and rac.png?

**Comment by racoon-supply-rac** [comment]
Sure done!

**Review by IbrarMakaveli — CHANGES_REQUESTED** [review]
Can you switch your token PR on assetlist frontier : `osmosis-frontier.assetlist.json`
Thanks !

**Comment by racoon-supply-rac** [comment]
> 

Should be good now! Added $RAC only in frontier-assetlist and removed from the other json. Let me know if this is what you meant

**Comment by IbrarMakaveli** [comment]
Great, tysm !

**Review by IbrarMakaveli — APPROVED** [review]

**Pull request merged**
