### PR TITLE
add SEASY ibc asset from juno to osmo

### PR DESCRIPTION
**Pull request by udit-gulati**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Looks good, added to chain reg, just awaiting addition to Frontend

**Comment by udit-gulati** [comment]
Hi @JeremyParish69, any update on the Frontend repo addition? Thanks.

**Comment by JeremyParish69** [comment]
> Hi @JeremyParish69, any update on the Frontend repo addition? Thanks.

Sorry, I wasn't very clear. I was waiting for SE team to create a PR to add the token to Osmosis Frontend. Please see this other PR to see how seJUNO and bJUNO were added.

**Comment by udit-gulati** [comment]
@JeremyParish69 https://github.com/osmosis-labs/osmosis-frontend/pull/794

**Pull request merged**
