### PR TITLE
Add Sommelier to asset list

### PR DESCRIPTION
**Pull request by hannydevelop**

### CODE REVIEW

**Comment by sunnya97** [comment]
Thanks @hannydevelop!  Can you also add a PR to the https://github.com/cosmos/chain-registry/ repo as well

**Comment by hannydevelop** [comment]
> Thanks @hannydevelop! Can you also add a PR to the https://github.com/cosmos/chain-registry/ repo as well

Great, I'll make a PR now

**Comment by JeremyParish69** [comment]
double-check value for display:  , might be a typo

**Comment by IbrarMakaveli** [comment]
Thanks, corrected :)

**Review by IbrarMakaveli — APPROVED** [review]

**Pull request merged**
