### PR TITLE
add crowdpunk dao token

### PR DESCRIPTION
**Pull request by sirnicolaz**
## Description

Adding CROWDP token, an ERC20 IBC coin from chain EVMOS.

CROWDP is the token of Crowdpunk DAO, legally recognized as Crowdpunk DAO OÜ. Some information:

- [Estonian Business Registry](https://ariregister.rik.ee/eng/company/16813917/Crowdpunk-DAO-O%C3%9C?search_id=94e98ff&pos=1)
- [GitHub](https://github.com/CrowdpunkDAO/contracts)
- [Website](https://www.crowdpunk.love/)
- Further information can be found in the [EVMOS governance proposal](https://wallet.keplr.app/chains/evmos/proposals/269) that allowed our token to become an IBC coin.

Adding pairs:

- CROWDP/OSMO
- CROWDP/USDC

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry). PR https://github.com/cosmos/chain-registry/pull/4300
- [x] Add asset to bottom of `zone_assets.json`.
- [ ] The addition of the asset to the EVMOS dashboard has also been requested https://github.com/evmos/chain-token-registry/pull/92

### On-chain liquidity

For each new asset, please provide the plan for on-chain liquidity of the asset: 

CROWDP/OSMO
- [x] Ready -- A liquidity pool has been created. The pool ID is: 1681 https://www.mintscan.io/osmosis/tx/93197862E792A50DF68B0E88DC97E4C8FC5EA4F39A49C487EE81524137E198A2?height=14848802&sector=logs
Further liquidity will be added once we have confirmation that the pool is fine

CROWDP/USDC
- [x] Ready -- A liquidity pool has been created. The pool ID is: 1682 https://www.mintscan.io/osmosis/tx/070E9233D98F4D1AF411008DD7D437B7E7235A36A361C1B77851C6CF33C8CAC0?height=14848938
Further liquidity  will be added once we have confirmation that the pool is fine

### CODE REVIEW

**Comment by sunnya97** [comment]
Please fix the merge conflicts

**Comment by JeremyParish69** [comment]
I'm not seeing this asset at https://app.evmos.org/assets
Is it going to be added there?

**Comment by sirnicolaz** [comment]
> I'm not seeing this asset at https://app.evmos.org/assets Is it going to be added there?

We are still waiting for them to integrate it, they said they are in the process. Should I comment here once that's done or open a new PR @JeremyParish69 ?

**Comment by JeremyParish69** [comment]
> > I'm not seeing this asset at https://app.evmos.org/assets Is it going to be added there?
> 
> We are still waiting for them to integrate it, they said they are in the process. Should I comment here once that's done or open a new PR @JeremyParish69 ?

Either will work. If you comment here, I will be able to create a new PR that sets the asset to being listed.

**Comment by forbesus** [comment]
Hello @JeremyParish69 
CROWDP token was listed on evmos

Could you please put crowdp on the list?

**Comment by JeremyParish69** [comment]
> Hello @JeremyParish69 CROWDP token was listed on evmos
> 
> Could you please put crowdp on the list?

Sure, will do.

Note that this asset will be listed on Osmosis Zone as an **Unverified** asset. If this asset should be upgraded to Verified status, please create another Pull Request to this repository to upgrade it (after reviewing the qualification criteria and requirements).
https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#upgrade-asset-to-verified-status-permissioned

**Comment by forbesus** [comment]
Thank you @JeremyParish69 
But crowdp was listed on cosmostation with demon `ibc/5EC896BED3EBCB2CB6F1C167582E4EFA3F6FA3385F28BA5EA92D4A489DA010C5`

https://github.com/cosmostation/chainlist/blob/c8f3c60726844d1ed8fd9ff6cb1535b6e869a364/chain/osmosis/assets.json#L3389

In osmosis, crowdp is showing wrong denom `ibc/DEE262653B9DE39BCEF0493D47E0DFC4FE62F7F046CF38B9FDEFEBE98D149A71`
image


Would you also check this?

**Comment by forbesus** [comment]
And cosmostation team is not using assets.json file anymore
Now they are using assets_2.json file now

https://github.com/cosmostation/chainlist/blob/ce83649df70327056f3375ed8e91d5eb8c50872a/chain/osmosis/assets_2.json#L7351

Thank you

**Comment by JeremyParish69** [comment]
> Thank you @JeremyParish69 But crowdp was listed on cosmostation with demon `ibc/5EC896BED3EBCB2CB6F1C167582E4EFA3F6FA3385F28BA5EA92D4A489DA010C5`
> 
> https://github.com/cosmostation/chainlist/blob/c8f3c60726844d1ed8fd9ff6cb1535b6e869a364/chain/osmosis/assets.json#L3389
> 
> In osmosis, crowdp is showing wrong denom `ibc/DEE262653B9DE39BCEF0493D47E0DFC4FE62F7F046CF38B9FDEFEBE98D149A71` image
> 
> Would you also check this?

Your screenshot is of the NEOK asset page, not the CROWDP asset page. I don't there is any error.

**Comment by JeremyParish69** [comment]
> And cosmostation team is not using assets.json file anymore Now they are using assets_2.json file now
> 
> https://github.com/cosmostation/chainlist/blob/ce83649df70327056f3375ed8e91d5eb8c50872a/chain/osmosis/assets_2.json#L7351
> 
> Thank you

Something is very wrong; the change from you looks incorrect and has to be reset

**Comment by JeremyParish69** [comment]
After further investigation, it looks like the replacement ibc hash is would it would be when replacing the contract from all lowercase to 0xfbF4318d24a93753F11d365A6dcF8b830e98Ab0F (with this specific set of uppercase characters). If this is the correct address, it should be corrected at the Cosmos Chain Registry.

**Comment by JeremyParish69** [comment]
> I am sorry image Here is crowdp screenshot `ibc/B87F0F5255CC658408F167C2F7B987A8D914622E1F73BCC267406360588F2B1E`

So this IBC hash denom is correct based on the registered contract. If this is incorrect, then the registration must be corrected as well.

**Comment by forbesus** [comment]
Okay, I am creating PR again

https://github.com/cosmos/chain-registry/pull/5617

Would you check this? @JeremyParish69

**Comment by JeremyParish69** [comment]
> Okay, I am creating PR again
> 
> [cosmos/chain-registry#5617](https://github.com/cosmos/chain-registry/pull/5617)
> 
> Would you check this? @JeremyParish69

Thanks, it's been merged now. After updating the Osmosis Zone assetlist, I can see that at least 1 pool has been detected, so the updated contract seems to be confirmed. Osmosis Zone should reflect the update shortly

**Comment by forbesus** [comment]
Thank you @JeremyParish69 
I think you will need #2080
How about you?

**Pull request merged**
