### PR TITLE
Remove Bitsong Fantokens

### PR DESCRIPTION
**Pull request by JeremyParish69**
because they are unlisted on Osmosis Zone.
would be really easy to re-add using data from the Chain Registry, if needed.
With these removed, automation and comparisons are easier since they are also not included in zone.osmosis.json

### CODE REVIEW

**Comment by jonator** [comment]
These were removed from our config, as well?

**Comment by JeremyParish69** [comment]
> These were removed from our config, as well?

No, I worry that with the existence of external incentives that it would appear better if there were valid token names and images. Would they simply not show up under external incentives if they were to be removed from config?

**Comment by JeremyParish69** [comment]
> Dear Jeremy, I was wondering if you could provide some information regarding the removal of BitSong fantokens. I noticed that they are no longer present on the asset lists of Osmosis, and I was curious to know if there is a specific reason for this. Could you kindly provide some clarification on this matter?

Hi Angelo. These tokens were removed because they are not listed on Osmosis (not on the Assets page). This assetlist is intended to eventually replace our file that specifies which tokens appear on the Assets place, thus we needed the files to align.

**Comment by angelorc** [comment]
Alright I see…If I send a PR with the new specifications could we at least add the fantokens on Frontier?

**Comment by JeremyParish69** [comment]
> Alright I see…If I send a PR with the new specifications could we at least add the fantokens on Frontier?

Are you referring to the pricing of the tokens? Or adding the tokens to the Assets page?

**Comment by angelorc** [comment]
Adding it to the assets and pool page

**Comment by angelorc** [comment]
@JeremyParish69

**Comment by JeremyParish69** [comment]
yes, that's fine

**Pull request merged**
