### PR TITLE
Add $BAD

### PR DESCRIPTION
**Pull request by xBadcoin**
### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
- [x] Add asset to bottom of `zone_assets.json`.
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_unlisted` defaults to `true` (until the respesentation and transferring of the new asset has been validated)

### On-chain liquidity

For each new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [x] Ready -- A liquidity pool has been created. The pool ID is: ______
- [ ] Soon -- A pool will be created. (See: [Pool Setup Guilde](https://docs.osmosis.zone/overview/integrate/pool-setup).)
  - [ ] (optional) A preview of the Osmosis Zone app with the new asset added is requested for creating the pool. (Supercharged Liquidity pools cannot be created via Osmosis Zone app)
- [ ] StreamSwap -- The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please see the checklist and add osmosis_unlisted: true

**Comment by JeremyParish69** [comment]
Also, your GitHub account is too new to enlist tokens. We'll need another GitHub user with a long and significant contribution history to comment on this PR to vouch for this token.

**Comment by JeremyParish69** [comment]
Is there a plan for liquidity? We'll be looking for the pool ID to be able to validate

**Comment by daniel-farina** [comment]
> Is there a plan for liquidity? We'll be looking for the pool ID to be able to validate

Hey @JeremyParish69, not involved but  I verified the hash is matching the original contract code, details here: https://gist.github.com/daniel-farina/416e25a059d4bb0ecb21163d3bce4c4c

**Comment by JeremyParish69** [comment]
> > Is there a plan for liquidity? We'll be looking for the pool ID to be able to validate
> 
> No plans for liquidity

Ok. I think we would be able to proceed once the checklist is complete and a pool is created (a requirement to listing). But since there is no plan for liquidity, should we close this PR for now, and revisit once you are ready to establish some initial liquidity?

**Comment by goddardneutron** [comment]
Nice

**Comment by xBadcoin** [comment]
> > > Is there a plan for liquidity? We'll be looking for the pool ID to be able to validate
> > 
> > 
> > No plans for liquidity
> 
> Ok. I think we would be able to proceed once the checklist is complete and a pool is created (a requirement to listing). But since there is no plan for liquidity, should we close this PR for now, and revisit once you are ready to establish some initial liquidity?

Pool/1380 Pool/1381

**Comment by lexomis** [comment]
would be great to see this merged now that the checklist has been completed!

**Pull request merged**
