### PR TITLE
Add Dyson Protocol to assetList and osmosis.zone

### PR DESCRIPTION
**Pull request by sybilsingleton**
This adds the Dyson Protocol asset and osmosis pool to osmosis-1.assetlist.json and osmosis.zone.json

### CODE REVIEW

**Comment by sybilsingleton** [comment]
Is there anything else needed to register the ibc denom as dys? 
https://frontier.osmosis.zone/pool/883

**Comment by JeremyParish69** [comment]
> Is there anything else needed to register the ibc denom as dys? https://frontier.osmosis.zone/pool/883

Please validate ibc deposit and withdraw, and check the tx explorer page:
https://osmosis-frontier-git-jp69-add-dys-osmo-labs.vercel.app/pool/883

**Comment by JeremyParish69** [comment]
also, do you have a circular token, @sybilsingleton ?

**Comment by sybilsingleton** [comment]
> Please validate ibc deposit and withdraw, and check the tx explorer page:
It worked for me  and looks good

> also, do you have a circular token, @sybilsingleton ?
Not yet, it's on the list of things to do, is it a blocker?

**Pull request merged**
