### PR TITLE
Updated price pool denom, removed unlisted pending approval

### PR DESCRIPTION
**Pull request by rbpollock**
## Description
Updating PAGE price pool info to ibc/23A62409E4AD8133116C249B1FA38EED30E500A115D7B153109462CD82C1CD99:1344
Requesting listed status

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
- [x] Add asset to bottom of `zone_assets.json`.
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_unlisted` defaults to `true` (until the respesentation and transferring of the new asset has been validated)

### On-chain liquidity

For each new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [x] Ready -- A liquidity pool has been created. The pool ID is: 1344
- [ ] Soon -- A pool will be created. (See: [Pool Setup Guilde](https://docs.osmosis.zone/overview/integrate/pool-setup).)
  - [ ] (optional) A preview of the Osmosis Zone app with the new asset added is requested for creating the pool. (Supercharged Liquidity pools cannot be created via Osmosis Zone app)
- [ ] StreamSwap -- The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

### CODE REVIEW

**Comment by rbpollock** [comment]
@JeremyParish69 - Thanks for all your awesome help. I've been struggling to figure out how to get price discovery working. One thing I noticed is that in the zone_assets the price/pool data is set as follows:

```json
      "keywords": [
        "osmosis-info",
        "osmosis-price:uosmo:1344",
        "osmosis-unlisted"
      ]
```
it looks like osmosis-price could be set to this and have the desired effect
```
osmosis-price:ibc/23A62409E4AD8133116C249B1FA38EED30E500A115D7B153109462CD82C1CD99:1344
```

Any direction for how to get this working would be super appreciated!

**Comment by JeremyParish69** [comment]
> @JeremyParish69 - Thanks for all your awesome help. I've been struggling to figure out how to get price discovery working. One thing I noticed is that in the zone_assets the price/pool data is set as follows:
> 
> ```json
>       "keywords": [
>         "osmosis-info",
>         "osmosis-price:uosmo:1344",
>         "osmosis-unlisted"
>       ]
> ```
> 
> it looks like osmosis-price could be set to this and have the desired effect
> 
> ```
> osmosis-price:ibc/23A62409E4AD8133116C249B1FA38EED30E500A115D7B153109462CD82C1CD99:1344
> ```
> 
> Any direction for how to get this working would be super appreciated!

Based on the reported liquidity and composition of pool 1344, I think the price for PAGE is likely working. The thing that isn't working yet is the swap router, so trading within these pools from the Osmosis frontend is not currently possible. Once that is fixed, our QA team will be able to validate token transfers and then we can get this listed.

**Comment by rbpollock** [comment]
> > @JeremyParish69 - Thanks for all your awesome help. I've been struggling to figure out how to get price discovery working. One thing I noticed is that in the zone_assets the price/pool data is set as follows:
> > ```json
> >       "keywords": [
> >         "osmosis-info",
> >         "osmosis-price:uosmo:1344",
> >         "osmosis-unlisted"
> >       ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it looks like osmosis-price could be set to this and have the desired effect
> > ```
> > osmosis-price:ibc/23A62409E4AD8133116C249B1FA38EED30E500A115D7B153109462CD82C1CD99:1344
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any direction for how to get this working would be super appreciated!
> 
> Based on the reported liquidity and composition of pool 1344, I think the price for PAGE is likely working. The thing that isn't working yet is the swap router, so trading within these pools from the Osmosis frontend is not currently possible. Once that is fixed, our QA team will be able to validate token transfers and then we can get this listed.

So just to verify, there is no way to make our token compatible with the existing swap router setup? Our team should wait until the swap router is updated then resubmit this PR?

**Comment by JeremyParish69** [comment]
> So just to verify, there is no way to make our token compatible with the existing swap router setup? Our team should wait until the swap router is updated then resubmit this PR?

Yes. Well, ideally Osmosis takes care of this on their own once they can complete validation themselves after being able to swap, but if they are slow to it, then you may submit a similar PR (or reopen this one).

**Pull request closed without merging**
