### PR TITLE
Adding token: CIF from chain Cifer - Update RPC and Rest endpoint

### PR DESCRIPTION
**Pull request by cifer-ai**
## Description

Based on our investigation of the previous chain registration issues about deposit and withdrawal, it appears there might be problems with RPC, REST, and WebSocket functionalities.

1. We've addressed a potential cause by adding https://app.osmosis.zone to the CORS allowed list configuration in .htaccess, as detailed in the attached screenshot:

Screenshot 2024-04-13 at 10 37 35 PM

2. Also disable CORS policies following this doc:
https://tutorials.cosmos.network/hands-on-exercise/4-run-in-prod/1-run-prod-docker.html#cors

3. Update RPC endpoint to the wss enable one.

4. Update Rest endpoint, by bypassing Cloudflare for the REST endpoint to see if it resolves the issue.

All of steps above should fix transferring problem.

### Adding Chains

If adding a new chain, please ensure the following:
- [x] Chain is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - Chain's registration must have `staking` defined, with at least one `staking_token` denom specified.
   - Chain's registration must have `fees` defined; at least one fee token has low, average, and high gas prices defined.
- [x] Add chain to bottom of `zone_chains.json`
   - RPC and REST must not have any CORS blocking of the Osmosis domain.
   - RCP node must have WSS enabled.

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - The `description` and/or `extended_description` of the asset in the Chain Registry is informative.
- [x] Add asset to bottom of `zone_assets.json`.
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_unlisted` defaults to `true` (until the respesentation and transferring of the new asset has been validated)
   - Note that it is recommended to include an X (fka, Twitter) profile URL with each asset.

### On-chain liquidity

For each new asset, please provide the plan for on-chain liquidity of the asset (See: [Pool Setup Guilde](https://docs.osmosis.zone/overview/integrate/pool-setup).): (choose one)
- [x] Ready -- A liquidity pool(s) has been created and has liquidity. The pool ID is: 1678,1680
- [ ] Soon -- A pool will be created soon. Do not merge this PR until liquidity is ready. 
  - [ ] (optional) A preview of the Osmosis Zone app with the new asset added is requested for creating the pool. (Note: This method is not recommended because the Supercharged Liquidity pool type cannot be created via the Osmosis Zone app)
- [ ] StreamSwap -- The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds. The StreamSwap Bootstrapping phase begins (when?): ______

### CODE REVIEW

**Comment by cifer-ai** [comment]
We test and still face the same issue after update. (CORS blocking and failed to connect with websocket)

We apologize for the ongoing deposit and withdrawal issues. 🙏
Our team is actively working on a fix to address the CORS configuration and restore functionality as soon as possible.

In the meantime, if you have any suggestion or similar cases, please don't hesitate to let us know. 🙏

**Comment by JeremyParish69** [comment]
An Update, I just noticed this error, so it looks like we require nodes serving over https instead of http.
image
Do we have nodes with https?

**Comment by cifer-ai** [comment]
Hi Jeremy,
Yes, we have RPC node with https, we will update and make a pull request.

However, we've identified a potential cause for deposit and withdrawal issues, where tokens are getting stuck in the relayer.

**Our Investigation:**
We identified two active channels between Cifer-2 and Osmosis-1 on Mintscan interface.
- The correct path (channel-39205 <> channel-1) is registered on the Cosmos chain registry. (https://github.com/cosmos/chain-registry/blob/master/_IBC/cifer-osmosis.json)
- The incorrect path (channel-39057 <> channel-0) appears to be a result of encountering errors during multiple attempts to create the relayer. We had to establish the connection successfully after several trials.
Channel-0 on Cifer-2 is designated for Cosmoshub, not Osmosis.
Screenshot 2567-04-16 at 21 18 46
Screenshot 2567-04-16 at 22 08 27

- Transactions show that CIF withdrawals from Osmosis use the incorrect channel (channel-39057), causing tokens to become stuck.
The transaction link: https://ibc.iobscan.io/transfers?pageNum=1&pageSize=10&denom=ibc/EFC1776BEFB7842F2DC7BABD9A3050E188145C99007ECC5F3526FED45A68D5F5&startTime=&endTime=2024-04-15
Screenshot 2567-04-16 at 21 19 49


**Proposed Solutions:**
Creating new clients won't address the root cause of the issue (incorrect channel on Cifer-2). We'd appreciate suggestions for moving forward:
1. Can we close the erroneous channel-39057 <> channel-0?
2. Can Osmosis Zone implement filtering to ensure the correct channel is used?

**Compensation:**
We will manually transfer stuck CIF tokens (as shown in the provided transaction link) to the intended destination wallets to compensate for this inconvenience.

**Next Steps:**
Please advise on the best course of action to resolve this issue and ensure smooth CIF deposits and withdrawals on Osmosis Zone.

**Comment by JeremyParish69** [comment]
Thanks for the investigation. Someone else had already claimed that Osmosis was using the wrong channel, but I've been unable to confirm whether this is the case recently, because of the nodes not being https.
I know that my initial attempt used the channel-39205 channel, so I'm not sure why some users are saying that Osmosis Zone is using the wrong channel...
image
I see that IOBscan shows the OSMO icon and chain-id with channel-39057, but are we certain this was triggered by Osmosis Zone and not some other interface?

**Comment by cifer-ai** [comment]
Hi Jeremy,

Thank you for the updates.
Regarding the incorrect channel issue, you're right, we can't confirm whether it originated from the Osmosis Zone UI or other interface.

Your initial attempt using channel-39205 resulted in an IBC timeout error. I suspect this might be related to our ongoing websocket connection issue, which we're actively troubleshooting with Google Cloud, our server provider.

To aid further investigation, I'll submit the following endpoints for your reference:

- HTTPS RPC: https://cif_node.cifer.ai
- REST Endpoint: https://api.cifer.ai

Please note that the websocket connection issue might persist for a few more days while troubleshooting continues.

I will continue to provide active updates as soon as we get further information. We apologize for any inconvenience this may cause.

**Comment by cifer-ai** [comment]
Hi Jeremy,

Following up on the withdrawal issue. I updated the HTTPS nodes and resolved the websocket connection problem on our end. However, I'm still encountering issues during withdrawal tests.

Here's what's different this time:

- Console logs don't show any websocket connection errors.
- There are no "Transaction failed" messages, but the transaction gets stuck in a loop of pending, failed, and pending refund.

Screenshot 2567-04-18 at 10 11 41
Screenshot 2567-04-18 at 10 13 36

- In console logs, while proceeding withdrawal, it shows "ERR_CONNECTION_CLOSED"
Screenshot 2567-04-18 at 10 13 28

- I checked the transaction on the explorer and found that the packet sequence is 16. I also verified on Hermes that the unreceived packet is showing as expected.
Screenshot 2567-04-18 at 10 15 23
Screenshot 2567-04-18 at 10 16 07

Also, transferring IBC tokens via Keplr also results in unreceived packets.

Given these observations, I'm unsure about the root cause.
As it's possible to be a relayer issue, I'll also raise this with the Hermes team for further investigation.
Any insights you can offer on this case would be much appreciated.

**Comment by JeremyParish69** [comment]
Thanks for providing thorough investigation details. I agree that it seems to most likely be issue with the relayer.

**Pull request merged**
