### PR TITLE
Upgrade Neutaro $NTMPI to Verified

### PR DESCRIPTION
**Pull request by Neutaro**
As requested by you we've created the pull request and changed the osmosis_verified field to true. The ID of the pool is #2211.
https://app.osmosis.zone/pool/2211

### Upgrading Asset to Verified

If upgrading an Asset to Verified, please see the requirements specified at [LISTING](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#upgrade-asset-to-verified-status-permissioned), and ensure the following:
- [x] Asset is defined thoroughly at the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - [x] A meaningful `description` (and `extended_description`, unless: meme, variant, or non-primary chain token).
   - [x] Associated `socials`, including `website` and `twitter` (unless: meme, variant, or non-primary chain token).
   - [x] **Logo Image** has a square Aspect Ratio, < 250 KB file size, and appropriate visual contrast with Osmosis Zone colors.
- [x]  **Liquidity**: This pool contains contains at least $1k USD-worth of liquidity of the asset (Provide Pool ID): ___https://app.osmosis.zone/pool/2211___ (Skip if alloy constituent)

'Verified' Status Validation Checklist (to be completed by Osmosis Zone maintainers):
- [x] Verify appearance and metadata
- [x] Accurate Price
- [x] Trading and routing functionality
- [x] Withdraw and Deposit
   - [x] Deposit Transaction URL (if in-app)

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please see the checklist and confirm that the requirements have been met.

**Comment by JeremyParish69** [comment]
Socials are not registered, the logo has a square background, but this feel like a circle might be more appropriate.
Withdraw does not work on Osmosis Zone. This may be due to reliability of the Neutaro endpoint.

**Comment by JeremyParish69** [comment]
Socials and extended_description are now registered.
Do we want to stick with the squared image?
image
No news on the reliability of IBC transfers--I assume it still doesn't work.

**Comment by Neutaro** [comment]
Hiho, sorry for the late reply. 
The IBC transfer is a weird one. Every time I try to manually send something across it just works. Do you happen to know what might be causing the issue on ososis.zone?

Something isn’t working…
Sorry for the inconvenience. Please refresh the page and try again or use an alternative application to transfer your funds to Osmosis.

This one. I currently have no idea where/ what to check to get it going.

Cheers

**Comment by Neutaro** [comment]
For the picture I will ask again if they want it changed. If they do I'll do another pull request.

**Comment by JeremyParish69** [comment]
I see repeated errors in the console with this endpoint, and I think that's why it won't proceed:
https://rpc2.neutaro.tech/cosmos/bank/v1beta1/balances/neutaro1...

**Comment by Neutaro** [comment]
Unless I'm missing something I think it's right that your query doesn't work. 
https://api2.neutaro.tech/cosmos/bank/v1beta1/balances/neutaro10wzvkc92p5y5lnvzlcf5k7c3zezz4dvtagay86
does work. You are using the RPC for that.

**Comment by JeremyParish69** [comment]
> Unless I'm missing something I think it's right that your query doesn't work. https://api2.neutaro.tech/cosmos/bank/v1beta1/balances/neutaro10wzvkc92p5y5lnvzlcf5k7c3zezz4dvtagay86 does work. You are using the RPC for that.

I see, the RPC and REST nodes were registered backwards: https://github.com/osmosis-labs/assetlists/blame/main/osmosis-1/osmosis.zone_chains.json#L1344

**Comment by Neutaro** [comment]
Oh, such a rookie mistake. My bad.
We'll keep the square picture for now and might update that at some point.

**Comment by JeremyParish69** [comment]
With the nodes swapped, the Withdrawal worked, but there seems to be CORS blocking. Deposits seem to be blocked on that CORS issue. Could you please double check the RPC node's CORS configuration? It seems the access control header should only specify just one origin (but * is there twice??).
image

**Comment by Neutaro** [comment]
Ok, I think the issue was that the nginx was set up to allow cors * and the node itself was also set to that. Apprently both the server and application settings will be added to the header. I've removed the server settings now. Hopefully that fixed it.

**Comment by Neutaro** [comment]
We've had this issue before. I have not yet figured out what causes it. But the withdraw works. 
Afaik the issue is that the application and server both have some cors settings and they both write to that header. I will do more digging and testing. But even when it says it fails, it goes through. I've withdrawn twice now.

**Comment by JeremyParish69** [comment]
I'm now able to deposit, but we still cannot establish a websocket connection
WebSocket connection to 'wss://rpc2.neutaro.tech/websocket' failed:
image

**Comment by Neutaro** [comment]
Working on the port forwarding so the websocket works. Not a server person, so might take a bit to figure out. But the websocket does work with rpc3. We had that issue before and this was the workaround I came up with. No forwarding on that rpc.

**Comment by JeremyParish69** [comment]
Want to bump this. This seemed quite close to the finish line, but also I think the node URLs have changed and might need to be updated here as well.

**Comment by Neutaro** [comment]
Hiho, yes it was very close to getting done, but then we had to move domains and that bricked a few things that I have to clean up now. I will comment on this again once I've updated it all and think this is ready to go on.
Thanks for your patience

**Comment by Neutaro** [comment]
Ok, I finally did it. The api/rpc-2.io and api/rpc-3.io work now, including the websocket. We have also updated the chain-registry.
@JeremyParish69 ( not sure if ping is needed, but just in case ).

**Comment by JeremyParish69** [comment]
> Ok, I finally did it. The api/rpc-2.io and api/rpc-3.io work now, including the websocket. We have also updated the chain-registry. @JeremyParish69 ( not sure if ping is needed, but just in case ).

Great! Which nodes should Osmosis Zone be looking at?

**Comment by Neutaro** [comment]
I'd say take rpc2.neutaro.io and api2.neutaro.io. I've also created a PR to update osmosis.zone_chains.json.

**Comment by JeremyParish69** [comment]
> I'd say take rpc2.neutaro.io and api2.neutaro.io. I've also created a PR to update osmosis.zone_chains.json.

Sorry, I just noticed that you already created a PR. Will update shortly

**Pull request merged**
