### PR TITLE
Mark FUND as a Verified Asset

### PR DESCRIPTION
**Pull request by refundvalidator**
Proposing to have the [FUND](https://www.coingecko.com/en/coins/unification) coin, the primary asset of the [Unification Chain](https://unification.com/) marked as a verified asset on Osmosis. 

Based on the Qualification Criteria mentioned in the [docs](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md), Unification should be an acceptable candidate, based on its Brand, Community, and Developer presences.

The Unification chain is one of the oldest chains within the Cosmos ecosystem, having its Mainchain debut in [2020](https://medium.com/unificationfoundation/introducing-fund-a0a562dc7f1b)

A public [repo](https://github.com/unification-com) housing all the source code for the chain itself, as well as the services enabled by the presence of the chain. Active community presences can be found on [Telegram](https://t.me/unificationfoundation) and [Discord](https://discord.gg/SeB69w5). 

Currently, there are two community driven pools available on Osmosis - [Pool #1240](https://app.osmosis.zone/pool/1240) and [Pool #1576](https://app.osmosis.zone/pool/1576)

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Thanks for the PR.
Qualification seems Ok, but can I please direct your attention to the [requirements section](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#requirements) of the Upgrade section of the LISTING doc? At a first glance, it seems much of the associated data isn't registered to the Chain Registry. I haven't checked CoinGecko or Integrations yet.

**Comment by refundvalidator** [comment]
> Thanks for the PR. Qualification seems Ok, but can I please direct your attention to the [requirements section](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#requirements) of the Upgrade section of the LISTING doc? At a first glance, it seems some of the associated data isn't registered to the Chain Registry (e.g., socials, extended description). CoinGecko is missing a Market Cap. I haven't checked other integrations yet.

I will review the current data we have in the registry and append accordingly. As for the market cap, Ill attempt again, but we have made a few attempts to fix the Market Cap evaluation a few times. Due to Unification's inflation rate is not fixed, and is determined by network usage of the services the chain offers, making providing endpoints a bit trickier.

**Comment by JeremyParish69** [comment]
Can I just ask that we register an `extended_description` and `socials` at the Chain Registry? We should be good to set as 'verified' from there.

**Comment by refundvalidator** [comment]
> Can I just ask that we register an `extended_description` and `socials` at the Chain Registry? We should be good to set as 'verified' from there. https://github.com/cosmos/chain-registry/blob/3fb7dda26ea5993723747883e4a74d0d4c37b484/unification/assetlist.json#L6

Apologies for the delays, I've made the changes you requested in this PR:
https://github.com/cosmos/chain-registry/pull/4390

**Pull request merged**
