### PR TITLE
Fix ORAI token

### PR DESCRIPTION
**Pull request by JeremyParish69**
update display denom

### CODE REVIEW

**Comment by kleimanb81** [comment]
Hi! So I had a quick question thar may be very simple. So we can see the token on frontier, deposits can be initiatives with correct balances, yet they timeout. Is this just a need to wait for it to be merged? Or should this issue not be present regardless

**Comment by JeremyParish69** [comment]
> Hi! So I had a quick question that may be very simple. So we can see the token on frontier, deposits can be initiatiated with correct balances, yet they timeout. Is this just a need to wait for it to be merged? Or should this issue not be present regardless

I don't think that issue is dependent on this. Sounds more like a relayer issue perhaps

**Comment by kleimanb81** [comment]
> 

I had a feeling so. Orai is managing their own relayers and they also utilize their own bridge for their dex. I haven't been able to speak to the team about it yet but it ibc transfers through keplr have been my only success, and some are still stuck. I'm not an expert on relaying and I'm a bit our of my league on where to begin on this issue. It could either be the need to establish a different relayer and endpoints, or it's being caused by the fact its utilizing their bridge (which I'm unsure the build) when attempting to deposit or withdraw (both fail). I could use some help in debugging the problem because I've never had a pr for ibc with native ibc and relayers I can't access the packet info for. This is an image sent to me from the team when I was working on the pr and they had relayer issues. They did clear the packet but if anything in there could help you diagnose a possible issue I'd appreciate the look. 

IMG_20220814_210719_668

**Comment by kleimanb81** [comment]
Sorry sunny you're gunna kill me, I'm on a new tg name and lost our old convo but @sunnya97 this is the ibc / relayer discussion if I DMed abour to some Rando and not you.

**Comment by ducphamle2** [comment]
@JeremyParish69 thank you for creating this PR. It lgtm. I can confirm that we are using ORAI as a display for exponent 6.

**Comment by ducphamle2** [comment]
> > 
> 
> I had a feeling so. Orai is managing their own relayers and they also utilize their own bridge for their dex. I haven't been able to speak to the team about it yet but it ibc transfers through keplr have been my only success, and some are still stuck. I'm not an expert on relaying and I'm a bit our of my league on where to begin on this issue. It could either be the need to establish a different relayer and endpoints, or it's being caused by the fact its utilizing their bridge (which I'm unsure the build) when attempting to deposit or withdraw (both fail). I could use some help in debugging the problem because I've never had a pr for ibc with native ibc and relayers I can't access the packet info for. This is an image sent to me from the team when I was working on the pr and they had relayer issues. They did clear the packet but if anything in there could help you diagnose a possible issue I'd appreciate the look.
> 
> IMG_20220814_210719_668

I have just got this covered. The channels & IBC denom of orai on Osmosis in the config are correct, so dont worry about it. Now we just need to maintain the IBC relayers. That's all

**Pull request merged**
