### PR TITLE
Add arkh

### PR DESCRIPTION
**Pull request by kynraze**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can you please add arkh to the osmosis-1.zone file?
Must not include 'osmosis-frontend' nor 'osmosis-info' without a pool defined in the zone file. Is there any ARKH pool?
Also, do you have a round SVG of the token logo the we can add to the Chain Registry? The only image in the Chain Registry is a rather low quality, unscalable, square image...

**Comment by kynraze** [comment]
yes, but how to fill pool? should I create it first or not?
I will look for the svg token logo

**Review by kynraze — COMMENTED** [review]
is this correct?

**Comment by JeremyParish69** [comment]
We'll also need to define an arkh-osmosis IBC channel in the chain registry: https://github.com/cosmos/chain-registry/tree/master/_IBC

**Comment by JeremyParish69** [comment]
> yes, but how to fill pool? should I create it first or not? I will look for the svg token logo I have the high quality image but I didnt have the svg file is it ok? [cosmos/chain-registry#1640](https://github.com/cosmos/chain-registry/pull/1640)

We'll be able to generate a staging link for you to use one everything else is in order (need IBC channels).
The better image quality helps, thanks. But still not as ideal as an SVG.

**Comment by JeremyParish69** [comment]
> is this correct?

That's a good start yes. But the tags in the assetlist file are also problematic. Could you please remove the addition to the assetlist file, and just keep the addition to the zone file?

**Comment by kynraze** [comment]
> > yes, but how to fill pool? should I create it first or not? I will look for the svg token logo I have the high quality image but I didnt have the svg file is it ok? [cosmos/chain-registry#1640](https://github.com/cosmos/chain-registry/pull/1640)
> 
> We'll be able to generate a staging link for you to use one everything else is in order (need IBC channels). The better image quality helps, thanks. But still not as ideal as an SVG.

I have SVG but it convert from png is it ok? https://github.com/cosmos/chain-registry/pull/1645

**Comment by JeremyParish69** [comment]
I'm so sorry, to keep asking things. I should also mention gas prices (low, average, and high)

**Comment by kynraze** [comment]
don update gas prices

**Comment by JeremyParish69** [comment]
You can use this staging link (https://osmosis-frontier-git-jp69-add-arkh-osmo-labs.vercel.app/) to confirm: IBC Deposit/Withdraw, Transaction Explorer page, Appearance/Image, Low gas fee works. And then create a pool, and please provide the Pool # so we can add it here in this PR (and I can use it to define the Price of ARKH)

**Comment by kynraze** [comment]
IBC isn't working, and my balance isn't showing up. I wonder why?

**Comment by JeremyParish69** [comment]
> IBC isn't working, and my balance isn't showing up. I wonder why?

you can contact me on Telegram @jeremyparish (or perhaps something else) for quick messaging. But can you be more specific about what's not working. Is it that you were able to initiate the transfer, but it's not going through, so it has to wait for timeout?

**Comment by kynraze** [comment]
dmed you

**Comment by kynraze** [comment]
pool-id : 954 QCK:OSMO

**Review by JeremyParish69 — APPROVED** [review]

**Pull request merged**
