### PR TITLE
add 8ball

### PR DESCRIPTION
**Pull request by 8bawl**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please remove the images on this PR. Please add explorers to the 8ball/chain.json in the chain registry.

**Comment by JeremyParish69** [comment]
I've created osmosis frontend PR to add 8ball: https://github.com/osmosis-labs/osmosis-frontend/pull/1345
Could you please validate deposit and withdrawal from the generated staging link?
https://osmosis-frontier-git-jp69-add-8ball-osmo-labs.vercel.app/

**Comment by 8bawl** [comment]
> I've created osmosis frontend PR to add 8ball: [osmosis-labs/osmosis-frontend#1345](https://github.com/osmosis-labs/osmosis-frontend/pull/1345) Could you please validate deposit and withdrawal from the generated staging link? https://osmosis-frontier-git-jp69-add-8ball-osmo-labs.vercel.app/

I tried to deposit 888 EBL from 8ball network to osmsosis
It said it would take 20 seconds to do the IBC transfer on channel-641

Deposit FAILED because it could not find the channel-641

Channel on 8ball network is channel-16

Is that a mistake somewhere?

**Comment by 8bawl** [comment]
tried again
UI says "transaction successful" with this transaction, 
https://explorer.8ball.info/8ball/tx/5C6F2E1BF9038E030C11A7EA3EFDAA47697FBFDEAB664DC8E3FEA726E408758C

but then deposit is never credited and says "Pending" then "Failed: Pending refund" in the "Transfer History"

**Comment by JeremyParish69** [comment]
> tried again UI says "transaction successful" with this transaction, https://explorer.8ball.info/8ball/tx/5C6F2E1BF9038E030C11A7EA3EFDAA47697FBFDEAB664DC8E3FEA726E408758C
> 
> but then deposit is never credited and says "Pending" then "Failed: Pending refund" in the "Transfer History"

Ah, OK. Wss needs to be enabled on the rpc node (https://rpc.8ball.info)

**Comment by 8bawl** [comment]
It was a CORS error on the rpc.8ball.info

- [x] Depsoit works

- [X] Withdraw works

Confirmed, thank you!

**Pull request merged**
