### PR TITLE
Add $VLO

### PR DESCRIPTION
**Pull request by Velosmo-1**
Files changed:
M	chain-registry
M	osmosis-1/osmosis-1.assetlist.json

},
{
"chain_name": "juno",
"base_denom": "cw20:jjuno1ezdrrmzk3d5ws86ux2wxuf7q5plgyp0upjryh4zcm96ufp7rp05qt2r2gu",
"path": "transfer/channel-169/cw20:juno1ezdrrmzk3d5ws86ux2wxuf7q5plgyp0upjryh4zcm96ufp7rp05qt2r2gu",
"pools": {
"OSMO": 975
},
"osmosis_main": false,
"osmosis_frontier": true,
"osmosis_info": true

### CODE REVIEW

**Comment by Velosmo-1** [comment]
https://user-images.githubusercontent.com/108884962/231899942-e16112e1-ffc8-4835-ad56-6a422c22f0b0.png

**Comment by Velosmo-1** [comment]
Hello I would like to do a PR like this to add my token and create the pool and create the pool with the Vercel
https://github.com/osmosis-labs/osmosis-frontend/pull/1462

**Comment by Velosmo-1** [comment]
DAO :
https://daodao.zone/dao/juno19te24a6cp2p59pltde6zkve6nykejjzg56pqvjz8wd3nkju3vfss8ljk76

**Comment by Velosmo-1** [comment]
https://user-images.githubusercontent.com/108884962/232102128-e0b08700-b5c9-41bd-8106-8b007f812b2c.svg

**Comment by JeremyParish69** [comment]
Please register VLO to the Chain Registry
https://github.com/cosmos/chain-registry/blob/master/juno/assetlist.json

**Pull request closed without merging**
