### PR TITLE
Upgrading PHMN Asset to Verified

### PR DESCRIPTION
**Pull request by albertandrejev**
## Description

See:
- IBCX/PHMN Pool 1254
- ATOM/PHMN Pool 1255
- WEIRD/PHMN Pool 1776
- PHMN/OSMO Pool 1738

### Upgrading Asset to Verified

If upgrading an Asset to Verified, please see the requirements specified at [LISTING](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#upgrade-asset-to-verified-status-permissioned), and ensure the following:
- [x] Asset is defined thoroughly at the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - [x] A meaningful `description` and `extended_description`.
   - [x] Associated `socials`, including `website` and `twitter`.
   - [x] Logo Image has a square Aspect Ratio and < 250 KB file size.
- [x] This pool contains contains at least $1k USD-worth of liquidity of the asset (Provide Pool ID): 1255

'Verified' Status Validation Checklist (to be completed by Osmosis Zone maintainers):
- [x] Verify appearance and metadata
- [x] Accurate Price
- [x] Trading and routing functionality
- [x] Withdraw and Deposit
   - [x] Deposit Transaction URL (if in-app)

### CODE REVIEW

**Comment by JeremyParish69** [comment]
I can't resolve your conflicts. Please stop the Query Pools Actions from running automatically on your fork

**Comment by albertandrejev** [comment]
> I can't resolve your conflicts. Please stop the Query Pools Actions from running automatically on your fork

done

**Comment by JeremyParish69** [comment]
> done

There are still too many conflicts. Can you please remove them or create a new branch?

**Comment by JeremyParish69** [comment]
Can I ask why did you tick items on the checklist that are not true? There is no extended description or socials at the chain registry.

**Comment by albertandrejev** [comment]
> Can I ask why did you tick items on the checklist that are not true? There is no extended description or socials at the chain registry.

I hope you checked right asset for these fields https://github.com/cosmos/chain-registry/blob/ef7879aaf7de2742bee79fa5bbb1444d516d27af/osmosis/assetlist.json#L6509, https://github.com/cosmos/chain-registry/blob/ef7879aaf7de2742bee79fa5bbb1444d516d27af/osmosis/assetlist.json#L6554 ? But maybe I missed something

**Comment by JeremyParish69** [comment]
> > Can I ask why did you tick items on the checklist that are not true? There is no extended description or socials at the chain registry.
> 
> I hope you checked right asset for these fields https://github.com/cosmos/chain-registry/blob/ef7879aaf7de2742bee79fa5bbb1444d516d27af/osmosis/assetlist.json#L6509, https://github.com/cosmos/chain-registry/blob/ef7879aaf7de2742bee79fa5bbb1444d516d27af/osmosis/assetlist.json#L6554 ? But maybe I missed something

Oh, I understand now. They were added to the Osmosis Assetlist, but it's needed on the original asset (in Juno's assetlist).

**Pull request closed without merging**
