### PR TITLE
Added Neutron to assetlist, zone_chains and zone_assets

### PR DESCRIPTION
**Pull request by luisqagt**
Added Neutron to frontier

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Thanks for this. Could you please focus on the zone_chains and zone_assets? as those will ask of everything we need to be able to enlist NTRN

**Comment by luisqagt** [comment]
Done @JeremyParish69

**Comment by JeremyParish69** [comment]
Is there any pool with NTRN yet? or will a preview link be needed to create that?

**Comment by JeremyParish69** [comment]
Validation reveals there is no neutron-osmosis IBC channel registered in the [Chain Registry](https://github.com/cosmos/chain-registry/tree/master/_IBC) (and there isn't any staking token registered either). Could we please get this registered first so it can pull all the necessary data?

**Comment by JeremyParish69** [comment]
I've created a preview link. Can you please let me know the pool id so I can configure the price and validate deposit/withdraw?

**Comment by luisqagt** [comment]
Getting this error @JeremyParish69 when trying to create the pool.

image

**Comment by luisqagt** [comment]
Managed to do it through CLI

https://osmosis-frontier-git-jp69-add-ntrn-2-osmo-labs.vercel.app/pool/1046

**Pull request merged**
