### PR TITLE
Make $CVN Verified

### PR DESCRIPTION
**Pull request by bitnet**
### Upgrading Asset to Verified

If upgrading an Asset to Verified, please see the requirements specified at [LISTING](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#upgrade-asset-to-verified-status-permissioned), and ensure the following:
- [x] Asset is defined thoroughly at the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - [x] A meaningful `description` and `extended_description`.
   - [x] Associated `socials`, including `website` and `twitter`.
   - [x] Logo Image has a square Aspect Ratio and < 250 KB file size.
- [x] This pool contains contains at least $1k USD-worth of liquidity of the asset (Provide Pool ID): ___1741___

'Verified' Status Validation Checklist (to be completed by Osmosis Zone maintainers):
- [ ] Verify appearance and metadata
- [ ] Accurate Price
- [ ] Trading and routing functionality
- [ ] Withdraw and Deposit
   - [ ] Deposit Transaction URL (if in-app)

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can you please add an extended_description to the registration?
https://github.com/cosmos/chain-registry/blob/master/conscious/assetlist.json#L6

**Comment by JeremyParish69** [comment]
Deposits do not work. CoinType 60 assets do not work with Osmosis Zone's IBC transfer mechanism, so we need an alternative interface to be able to Deposit.

**Comment by bitnet** [comment]
> Can you please add an extended_description to the registration? https://github.com/cosmos/chain-registry/blob/master/conscious/assetlist.json#L6

ok

**Comment by bitnet** [comment]
https://github.com/cosmos/chain-registry/pull/4608

**Comment by bitnet** [comment]
> Deposits do not work. CoinType 60 assets do not work with Osmosis Zone's IBC transfer mechanism, so we need an alternative interface to be able to Deposit.

Yes, it will prompt failure when sending the transaction. Is there anything I need to do?

**Comment by bitnet** [comment]
Currently, deposits can be completed through the advanced IBC transfer function of the keplr wallet

**Comment by JeremyParish69** [comment]
> Yes, it will prompt failure when sending the transaction. Is there anything I need to do?

Yes, we need an interface (that's not a wallet extension) where users can complete Deposits

**Comment by bitnet** [comment]
> > Yes, it will prompt failure when sending the transaction. Is there anything I need to do?
> 
> Yes, we need an interface (that's not a wallet extension) where users can complete Deposits

Ok

**Comment by bitnet** [comment]
@JeremyParish69 Hi

We provide a deposit function on this page, which is somewhat hidden

https://dao.cvn.io/conscious?openModal=true

image

**Comment by bitnet** [comment]
@JeremyParish69 please try again

**Comment by JeremyParish69** [comment]
> @JeremyParish69 please try again

I now see that the failed transfer attempt finally refunded the amount, but the UX is just as bad as it was. What's different about it?

**Comment by JeremyParish69** [comment]
I believe hybrid evm chains now work with Osmosis Zone IBC transfer, but now it seems that the IBC client has expired. Will this be revived?

**Comment by JeremyParish69** [comment]
IBC client expired. PR Stale

**Pull request closed without merging**
