### PR TITLE
Mark PURSE as a Verified Asset

### PR DESCRIPTION
**Pull request by zakir-code**
* https://twitter.com/Purse_Land

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Please see the latest requirements for verified status:
https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#requirements

**Comment by JeremyParish69** [comment]
If we can have these values added or improved at the Chain Registry, (and sufficient liquidity) we'll be able to proceed with setting as verified.
image

**Comment by zakir-code** [comment]
https://github.com/cosmos/chain-registry/pull/4405

**Comment by JeremyParish69** [comment]
I was unable to find this address on StarScan.
I'm guessing you copied the corresponding address from Ethereum/BSC, but that it's not the address on PundiX. I think this is a sdk.coin token, minting by the bridging from BSC, but that there is no contract address on the Pundi X Chain side, and the type_asset aught to be updated to sdk.coin and and address aught to be deleted.
Or am I somehow missing the contract on the Pundi X Chain?

**Comment by zakir-code** [comment]
Yes, I misunderstood `type_asset` as short. This address is on BSC, and evm is not integrated on the pundix chain.

https://github.com/cosmos/chain-registry/pull/4415

**Comment by JeremyParish69** [comment]
I didn't clue in before, it seems the asset is still unlisted. It might be because we never had transfers working.

**Comment by JeremyParish69** [comment]
Yes, investigating further, I cannot complete Deposit validation because there is not PUNDIX liquidity on Osmosis

**Pull request merged**
