### PR TITLE
fix: Add $USK to osmosis-1.assetlist.json

### PR DESCRIPTION
**Pull request by silvermind**
Add $USk with same values as in osmosis-frontier.assetlist.json to make Token visible in the already working pool https://app.osmosis.zone/pool/819

On the frontier pages, it already correctly shows the token on the swap dialog: https://frontier.osmosis.zone/pool/819

### CODE REVIEW

**Comment by JeremyParish69** [comment]
> Add $USk with same values as in osmosis-frontier.assetlist.json to make Token visible in the already working pool https://app.osmosis.zone/pool/819
> 
> On the frontier pages, it already correctly shows the token on the swap dialog: https://frontier.osmosis.zone/pool/819

Thanks for the contribution. Could we instead add this to the frontier file (and not add to this file) since that's where it is?

**Comment by silvermind** [comment]
not sure what you mean, it's already in the frontier file, trading also work via this url https://app.osmosis.zone/pool/819 but on the non frontiert app in the "swap token" popup the icon and name is broken, thought this would fix that..

**Comment by JeremyParish69** [comment]
> not sure what you mean, it's already in the frontier file, trading also work via this url https://app.osmosis.zone/pool/819 but on the non frontiert app in the "swap token" popup the icon and name is broken, thought this would fix that..

Ah, yes, it is in the frontier file. However, it should not go in the osmosis-1 file unless it's listed on the Main site, which USK is not at the moment.

The data for the token is meant to be available to both versions of the site (main and frontier), so if there is any error displaying the token, that would instead be a bug in the frontend code. Changes in this repo would not fix that.

**Comment by JeremyParish69** [comment]
@silvermind Are there any pools with USK?

**Comment by JeremyParish69** [comment]
USK is on Osmosis Frontier. USK was added to assetlists repo in another PR and the pool was defined for it.

**Pull request closed without merging**
