### PR TITLE
Add NEXX

### PR DESCRIPTION
**Pull request by NEXXGENAI**
### Adding Assets

If adding a new asset, please ensure the following:
- [x] Add to bottom of zone_assets.json
- [x] `osmosis_main` defaults to `false` (or else cite the listing rule that justifies enlisting to the Main app)
- [x] The IBC channel referenced in `path` has been registered to the Chain Registry.

### Validation Testing

If adding a new asset, the **Deposit** and **Withdraw** functions (and the link to the transaction on the foreign chain's block explorer) for the asset must be validated before listing. Please specify whether the Osmosis assetlists repo maintainers [x]or the submitting team shall validate: (choose one)
- [ ] Submitting team to validate--a preview link is requested in the comments of this PR. The submitting team will provide evidence of success of the Deposit and Withdraw functions from the Preview Frontend. (screenshot + tx url)

OR
- [x] Osmosis assetlists repo maintainers to validate--testers will need a small amount of tokens to validate. In which case:
  - [ ] Validaters can buy a small amount of this asset from Pool ID: {PROVIDE POOL ID}.

### On-chain liquidity

If adding a new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [ ] The submitting team will ensure a pool will be created soon. Please hold off until further communication, which will notify of the Pool ID.

OR
- [ ] A preview link is requested for the submitting team to be able to create a pool using the Osmosis Frontend.

OR
- [x] The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

OR
- [ ] Other--<elaborate>

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Can you please specify the plan for validation and liquidity?

**Comment by NEXXGENAI** [comment]
Hi Jeremy, thank you for your recent contributions.  The Osmosis assetlists repo maintainers will validate and we will be launching a stream on Streamswap

**Comment by JeremyParish69** [comment]
> Hi Jeremy, thank you for your recent contributions. The Osmosis assetlists repo maintainers will validate and we will be launching a stream on Streamswap

Thanks for the info. Can we set this to draft until the Bootstrapping phase? Can I ask when the Stream will be?

**Comment by NEXXGENAI** [comment]
No, we've been asked by Streamswap to add NEXX before they take it forward.

**Comment by NEXXGENAI** [comment]
> > Hi Jeremy, thank you for your recent contributions. The Osmosis assetlists repo maintainers will validate and we will be launching a stream on Streamswap
> 
> Thanks for the info. Can we set this to draft until the Bootstrapping phase? Can I ask when the Stream will be?

Yes, thank yo for doing that..  We've been asked by Streamswap to move this over to Osmosis testnet for them to take it forward.  Are there any references to refer to that show how to do that?  Thanks

**Comment by JeremyParish69** [comment]
@NEXXGENAI You're asking for helping on getting your testnet token to show up on Osmosis Testnet frontend? You can replace the tokenfactory denom with the testnet denom, and simply place this edit into the osmosistestnet-5 folder. But it should first be registered to the Cosmos Chain Registry under junotestnet.

**Comment by JeremyParish69** [comment]
@NEXXGENAI 
OK NEXX is now added to the Chain Registry.
Most of these changes are not needed (and are incorrect)--we only needed the osmo-test-5/zone_assets.json file updated.
We generally don't accept requests from new GitHub accounts, but I believe a StreamSwap launch would qualify this for listing.

**Comment by NEXXGENAI** [comment]
> @NEXXGENAI OK NEXX is now added to the Chain Registry. Most of these changes are not needed (and are incorrect)--we only needed the osmo-test-5/zone_assets.json file updated. We generally don't accept requests from new GitHub accounts, but I believe a StreamSwap launch would qualify this for listing.

Thanks Jeremy, much appreciated

**Comment by NEXXGENAI** [comment]
> @NEXXGENAI 
> OK NEXX is now added to the Chain Registry.
> Most of these changes are not needed (and are incorrect)--we only needed the osmo-test-5/zone_assets.json file updated.
> We generally don't accept requests from new GitHub accounts, but I believe a StreamSwap launch would qualify this for listing.

@JeremyParish69 

Please review changes made to the Osmo-test-5/osmosis.zone_assets file.

Thank you

**Review by NEXXGENAI — COMMENTED** [review]
Perfect

**Pull request closed without merging**
