### PR TITLE
add SEIYAN Asset

### PR DESCRIPTION
**Pull request by Fscare**
## Description

Adding SEIYAN token a memecoin from Sei Chain.

Some information:

[SEIYAN Twitter](https://twitter.com/seiyantoken9000
)
[SEIYAN Website](https://seiyantoken.com/)

SEIYAN/SEI pair will be added soon.

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - The `description` and/or `extended_description` of the asset in the Chain Registry is informative.
- [x] Add asset to bottom of `zone_assets.json`.
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_unlisted` defaults to `true` (until the respesentation and transferring of the new asset has been validated)
   - Note that it is recommended to include an X (fka, Twitter) profile URL with each asset.

### On-chain liquidity

For each new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [ ] Ready -- A liquidity pool has been created. The pool ID is: ______
- [x] Soon -- A pool will be created. (See: [Pool Setup Guilde](https://docs.osmosis.zone/overview/integrate/pool-setup).)
  - [ ] (optional) A preview of the Osmosis Zone app with the new asset added is requested for creating the pool. (Supercharged Liquidity pools cannot be created via Osmosis Zone app)
- [ ] StreamSwap -- The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

### CODE REVIEW

**Comment by Fscare** [comment]
> chain name is wrong. `seiyan` isn't the chain, `sei` is

Sorry, fixed it now

**Comment by JeremyParish69** [comment]
please add `"osmosis_unlisted": true`
Please let us know what the pool ID and we will proceed

**Comment by Feraxion** [comment]
> please add `"osmosis_unlisted": true` Please let us know what the pool ID and we will proceed

SEIYAN/OSMO pair pool ID is 1593 (actually deployed 1592 but IBC/xxx was in lowercase so deployed again)

**Comment by Fscare** [comment]
> please add `"osmosis_unlisted": true` Please let us know what the pool ID and we will proceed

SEIYAN/OSMO pair pool ID is 1593 (actually deployed 1592 but IBC/xxx was in lowercase so deployed again)

**Pull request closed without merging**
