### PR TITLE
Added BeeZee(BZE) coin

### PR DESCRIPTION
**Pull request by faneaatiku**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
BZE has not yet been added to Osmosis Frontend, and therefore shouldn't be merged yet. In addition, this PR tries to add the token to the main file, when it should first only be included into the Frontier file. Are there plans top add this token to the Osmosis Frontend repo soon?

**Comment by faneaatiku** [comment]
> BZE has not yet been added to Osmosis Frontend, and therefore shouldn't be merged yet. In addition, this PR tries to add the token to the main file, when it should first only be included into the Frontier file. Are there plans top add this token to the Osmosis Frontend repo soon?

Hi. Sorry for the late answer, somehow I didn't received the notification about your comment. Where do I have to submit the PR ? 

i haven't followed mainly because our channel expired and we had to solve that first. If you could guide me a bit I'd be more than happy to start working on another PR. 

Thanks in advance.

**Comment by JeremyParish69** [comment]
@faneaatiku It's OK I'll be happy to guide you. First we'll need to make sure to have the current ibc channel information, so please confirm that this is up to date, and it's best to have the id # of a OSMO/BZE pool (or at least another pool with BZE). I'll be able to help out on the Frontend repo as long as all the info is available.

If you need to chat I can be reached on TG @jeremyparish

**Comment by faneaatiku** [comment]
> 

I can confirm that the IBC details are up to date. We managed to update our IBC client and tested transfers between the two chains. 
I recreated the source branch since in the meanwhile frontier file was removed.

**Comment by faneaatiku** [comment]
> @faneaatiku It's OK I'll be happy to guide you. First we'll need to make sure to have the current ibc channel information, so please confirm that this is up to date (should be updated in Chain Registry as well), and it's best to have the id # of a OSMO/BZE pool (or at least another pool with BZE). I'll be able to help out on the Frontend repo as long as all the info is available.
> 
> If you need to chat I can be reached on TG @jeremyparish

Is this the PR you were talking about https://github.com/osmosis-labs/osmosis-frontend/pull/1091 ? 

thanks in advance!

**Pull request merged**
