### PR TITLE
Make wLIBRA Verified

### PR DESCRIPTION
**Pull request by JeremyParish69**
## Description

Make wLIBRA Verified
adds Deposit/Withdraw Override to LibreBridge

### Upgrading Asset to Verified

If upgrading an Asset to Verified, please see the requirements specified at [LISTING](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#upgrade-asset-to-verified-status-permissioned), and ensure the following:
- [x] Asset is defined thoroughly at the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - [x] A meaningful `description` and `extended_description`.
   - [x] Associated `socials`, including `website` and `twitter`.
   - [x] Logo Image has a square Aspect Ratio and < 250 KB file size.
- [x] This pool contains contains at least $1k USD-worth of liquidity of the asset (Provide Pool ID): [1721](https://app.osmosis.zone/pool/1721)

'Verified' Status Validation Checklist (to be completed by Osmosis Zone maintainers):
- [x] Verify appearance and metadata
- [x] Accurate Price
- [x] Trading and routing functionality
- [x] Withdraw and Deposit (LibraBridge)

### CODE REVIEW

**Review by zmanian — APPROVED** [review]

**Comment by JeremyParish69** [comment]
@zmanian we're blocked on correcting the registration https://github.com/cosmos/chain-registry/pull/4522 (might you be able to confirm this?) and the bridge actually working (didn't work for our QA team)

**Comment by zmanian** [comment]
Bridge seems to be working for community members. I've bridged at lest 4 times.

Micro libra is the base Denom.

Community is complaining cause the logo got downscaled to 32x32 in front end.
 How do I fix that?

**Comment by JeremyParish69** [comment]
When asking the base, I'm asking about how exactly the chain's code refers to it. Is it "Micro libra" or "microlibra" or "uLibra" or "ulibra"?

**Comment by JeremyParish69** [comment]
That's the frontend's compression, I don't think it has anything to do with the size or quality at the Chain Registry in this case.

**Comment by siliconbits** [comment]
> When asking the base, I'm asking about how exactly the chain's code refers to it. Is it "Micro libra" or "microlibra" or "uLibra" or "ulibra"?

The unit is "microlibra"

Reference: https://github.com/search?q=org%3A0LNetworkCommunity+microlibra&type=code

**Comment by siliconbits** [comment]
Can the logo generated by Osmosis please be refreshed to match the updated Cosmos Chain Registry images too 🙇‍♂️

**Pull request merged**
