### PR TITLE
Update "display" variable in assetlist

### PR DESCRIPTION
**Pull request by IbrarMakaveli**
On the assetlist, we should have a variable that defines the name of the project : for example Cosmos for ATOM, this should be for me the role of the “display” variable in the assetlist.

### CODE REVIEW

**Comment by Thunnini** [comment]
So basically, assetlist is made by referencing how `bank` module defines metadata. Referencing https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-024-coin-metadata.md , I think the current way that's done is correct. The `display` field should be pointing towards the `denom` field, while the actual display name is illustrated in the symbol field

**Comment by sunnya97** [comment]
I agree with @Thunnini that the display is meant to be a reference to one of the denoms.

However, I think you're right that these "Project Names" are useful.  Maybe we should just replace what's currently used as "description"?

Currently "description" is this pretty non-standardized, longer sentence, that I'm not sure belongs in an assetlist.  Maybe replacing those with the names you suggest is better?

**Comment by sunnya97** [comment]
@Thunnini @IbrarMakaveli I updated the PR with my proposal. Wdyt about this?

**Comment by IbrarMakaveli** [comment]
@sunnya97 I'm more in favor of creating a new variable personally ("project_name" or "name"), the "description" key today is a bit the same everywhere actually, but you can change it and ask the project a small description (like max 50 words).
Moreover "description" as key with the project name is a bit confusing personally, we expect a "description" (short presentation) as value.

@ValarDragon @Thunnini What do you think about it?

**Comment by sunnya97** [comment]
Probably a character limit rather than a word limit I think.

Problem is it just feels less "objective" to me.  Like what happens when everyone starts adding all this stuff about like "valueless governance token" yada yada to the description.  Is that going to be valuable?

**Comment by IbrarMakaveli** [comment]
Yes it is true that it does not bring value (on the list), moreover we will have to manage the moderation of adding new tokens description on the list (and try to be "objective"). Maybe we can leave "description" for now and not use it and keep a neutral format as it is now ?

**Comment by sunnya97** [comment]
@IbrarMakaveli if we're adding a new field, can you please also update the json scheme

https://github.com/osmosis-labs/assetlists/blob/main/assetlist.schema.json

**Comment by IbrarMakaveli** [comment]
@sunnya97 @Thunnini Yes, it's done, I let you guys review it

**Pull request merged**
