### PR TITLE
bostrom: added other native tokens

### PR DESCRIPTION
**Pull request by bro-n-bro-0**
### Adding Chains

If adding a new chain, please ensure the following:
- [x] Chain is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).

  Note:
   - Chain's registration must have `staking` defined, with at least one `staking_token` denom specified.
   - Chain's registration must have `fees` defined; at least one fee token has low, average, and high gas prices defined.
- [x] Add chain to bottom of `zone_chains.json`

  Note:
   - RPC and REST must not have any CORS blocking of the Osmosis domain.
   - RCP node must have WSS enabled.

### Adding Assets

If adding a new asset, please ensure the following:
- [x] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
- [x] Add asset to bottom of `zone_assets.json`.

  Note:
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_main` defaults to `false` (or else cite the listing rule that justifies enlisting to the Main app)

### On-chain liquidity

If adding a new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [ ] The submitting team will ensure a pool will be created soon. Please hold off until further communication, which will notify of the Pool ID. (Please set the PR's status to Draft until the pool has been created)

OR
- [x] A preview link is requested for the submitting team to be able to create a pool using the Osmosis Frontend.

OR
- [ ] The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

### Validation Testing

If adding or updating a chain or asset, the changes must be validated from the updated build of the Osmosis Frontend. Testers will need a small amount of tokens to validate. 
  - [ ] Validaters can buy a small amount of this asset from Pool ID: {PROVIDE POOL ID}.
  - [ ] Preview build has been validated.

### CODE REVIEW

**Comment by bro-n-bro-0** [comment]
@JeremyParish69 
Hey! 
How quickly I can see the new assets on the osmosis front? 

I want to add liquidity and then add an external incentives

**Comment by JeremyParish69** [comment]
> @JeremyParish69 Hey! How quickly I can see the new assets on the osmosis front?
> 
> I want to add liquidity and then add an external incentives

You can use this Preview build to add liquidity. Please confirm the Pool IDs so I can add them in the frontend.
Note that creating Supercharged Liquidity pools (the preferred pool type) and creating and adding to incentive gauges can only be done via CLI.

**Comment by bro-n-bro-0** [comment]
@JeremyParish69 Hey! 

I've added a small amount to the SLP:

https://app.osmosis.zone/pool/1302
https://app.osmosis.zone/pool/1303
https://app.osmosis.zone/pool/1304

Can you add  HYDROGEN, V, and A to the asset list on the osmosis frontend?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 Hey!
> 
> I've added a small amount to the SLP:
> 
> https://app.osmosis.zone/pool/1302 https://app.osmosis.zone/pool/1303 https://app.osmosis.zone/pool/1304
> 
> Can you add HYDROGEN, V, and A to the asset list on the osmosis frontend?

Sure https://github.com/osmosis-labs/assetlists/pull/804
No TOCYB?

**Comment by bro-n-bro-0** [comment]
> > @JeremyParish69 Hey!
> > I've added a small amount to the SLP:
> > https://app.osmosis.zone/pool/1302 https://app.osmosis.zone/pool/1303 https://app.osmosis.zone/pool/1304
> > Can you add HYDROGEN, V, and A to the asset list on the osmosis frontend?
> 
> Sure #804 No TOCYB?

Tocyb too
But there is no pool
Will make it tmrw

**Comment by bro-n-bro-0** [comment]
@JeremyParish69 Hey! 

The pool with the TOCYB is added https://app.osmosis.zone/pool/1310
But something is wrong with the tocyb icon :(

So may I ask you to add to the frontend tocyb too?
Also, I would like to ask, what is supposed to be done to switch verified asset value to true?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 Hey!
> 
> The pool with the TOCYB is added https://app.osmosis.zone/pool/1310 But something is wrong with the tocyb icon :(
> 
> So may I ask you to add to the frontend tocyb too? Also, I would like to ask, what is supposed to be done to switch verified asset value to true?

Ok, I've updated to have TOCYB listed now that it has a pool.

Please see the [listing guidelines](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md) for info about the 'verified' status.

**Comment by bro-n-bro-0** [comment]
> > @JeremyParish69 Hey!
> > The pool with the TOCYB is added https://app.osmosis.zone/pool/1310 But something is wrong with the tocyb icon :(
> > So may I ask you to add to the frontend tocyb too? Also, I would like to ask, what is supposed to be done to switch verified asset value to true?
> 
> Ok, I've updated to have TOCYB listed now that it has a pool.
> 
> Please see the [listing guidelines](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md) for info about the 'verified' status.

@JeremyParish69 

Yep, I saw that. The BOOT token as a staking token of the Bostrom network was verified 2 years ago. A, V, HYDROGEN, and TOCYB were and are the native tokens of Bostrom from the beginning. So is there any chance to verify them without additional paperwork? Also, I've prepared tokens for adding external incentives and it is better for me to add this only after assets visibility.

**Comment by JeremyParish69** [comment]
> @JeremyParish69
> 
> Yep, I saw that. The BOOT token as a staking token of the Bostrom network was verified 2 years ago. A, V, HYDROGEN, and TOCYB were and are the native tokens of Bostrom from the beginning. So is there any chance to verify them without additional paperwork? Also, I've prepared tokens for adding external incentives and it is better for me to add this only after assets visibility.

I don't see any obvious qualifiers so I think it's best to submit to the form.

**Comment by bro-n-bro-0** [comment]
> > @JeremyParish69
> > Yep, I saw that. The BOOT token as a staking token of the Bostrom network was verified 2 years ago. A, V, HYDROGEN, and TOCYB were and are the native tokens of Bostrom from the beginning. So is there any chance to verify them without additional paperwork? Also, I've prepared tokens for adding external incentives and it is better for me to add this only after assets visibility.
> 
> I don't see any obvious qualifiers so I think it's best to submit to the form.

Got it
I've submitted form for all assets

**Pull request merged**
