### PR TITLE
fix: update asset dhp-dHealth

### PR DESCRIPTION
**Pull request by nsonanh**
Ref: https://github.com/cosmos/chain-registry/pull/4534

### CODE REVIEW

**Comment by nsonanh** [comment]
@JeremyParish69 could you please review this PR ?

**Comment by nsonanh** [comment]
@JeremyParish69 Can you please take a look ? Is there anything we need to update ? 
We need this merged to create the pool right away after, as our community is querying about this for a while :pray:

**Comment by JeremyParish69** [comment]
Should be updated now

**Comment by nsonanh** [comment]
@JeremyParish69 Depositing DHP is still using the old channel (channel-2) instead of channel-4. Do you think it hasn't updated yet ?
image

**Comment by JeremyParish69** [comment]
It wasn't updated at that time, but a fix has been pushed and this should be resolved by now.

**Comment by nsonanh** [comment]
@JeremyParish69 It's working now, thanks! :+1:

**Pull request merged**
