### PR TITLE
verify aioz and sail

### PR DESCRIPTION
**Pull request by sunnya97**
### Upgrading Asset to Verified

If upgrading an Asset to Verified, please see the requirements specified at [LISTING](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#upgrade-asset-to-verified-status-permissioned), and ensure the following:
- [x] Asset is defined thoroughly at the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - [x] A meaningful `description` and `extended_description`.
   - [x] Associated `socials`, including `website` and `twitter`.
   - [x] Logo Image has a square Aspect Ratio and < 250 KB file size.
- [x] This pool contains contains at least $1k USD-worth of liquidity of the asset (Provide Pool ID): ______

'Verified' Status Validation Checklist (to be completed by Osmosis Zone maintainers):
- [x] Verify appearance and metadata
- [x] Accurate Price
- [x] Trading and routing functionality
- [x] Withdraw and Deposit
   - [x] Deposit Transaction URL (if in-app)

### CODE REVIEW

**Comment by JeremyParish69** [comment]
These are the point's I'd ask the teams to look into before verifying:
SAIL's image is 441 KB, which is quite large.
There doesn't seem to be any liquidity of SAIL; without liquidity of SAIL, it doesn't have a price, and it's TIP doesn't have a chart.
And low liquidity of AIOZ (only $500-worth of AIOZ in pool 1565).

**Comment by sunnya97** [comment]
There is 25k of liquidity for SAIL

CleanShot 2024-04-24 at 15 50 57@2x

**Comment by JeremyParish69** [comment]
> There is 25k of liquidity for SAIL

My mistake, I should have looked there as well, and not just the assetlist which doesn't detect WW or PCL pools yet.
Interestingly, this check did reveal some likely errors in regard to SAIL's pricing--will investigate further.

**Comment by JeremyParish69** [comment]
I've since added a CoinGecko ID for Sail, so it has a price now (even though the pool's liquidity value is still showing only half of what it actually is (more like $50k), since Data doesn't have an on-chain data for SAIL price.
I'd like for that liquidity value to be accurate first, but I guess we're OK to proceed.

**Comment by JeremyParish69** [comment]
The outlook seems like the SAIL pool won't have a volume for quite some time because Numia hasn't added support for WW pool type. Proceeding with marking a verified because everything else is in order and they don't deserve to be stuck as unverified for our incomplete infra support.

**Pull request merged**
