### PR TITLE
Add impacthub to Osmo-test-5 assets and chains

### PR DESCRIPTION
**Pull request by Michael-Ixo**
Add Impacthub (Ixo) to Osmo-test-5/osmosis.zone_assets and Osmo-test-5/osmosis.zone_chains

## Description

Adding chain: impacthubtestnet (Ixo)
Adding token: uxio from chain Ixo

### Adding Chains

Adding ImpacthubTestnet to chain registry is in pr(https://github.com/cosmos/chain-registry/pull/2854), opening this pr so long to make sure everything is okay. 

### Adding Assets

Asset is already on chain registry, made a pr to add tesnet ibc channel in pr(https://github.com/cosmos/chain-registry/pull/2854)

### On-chain liquidity

If adding a new asset, please provide the plan for on-chain liquidity of the asset: 
- [ *] The submitting team will ensure a pool will be created soon. Please hold off until further communication, which will notify of the Pool ID. 
I can provide a lot of uixo ibc tokens for the pool, just not sure how to get 1000osmo tokens on tesnet to create the pool?

### CODE REVIEW

**Comment by Michael-Ixo** [comment]
Chain registry pr's is merged so just this one now :)

**Comment by Michael-Ixo** [comment]
@JeremyParish69 what is next steps here?

**Comment by JeremyParish69** [comment]
> this one now :)

The fee aught to be corrected but for the near term I'm looking for testnet tokens

**Comment by JeremyParish69** [comment]
> @JeremyParish69 what is next steps here?

In the meantime I can give you 1000 testnet OSMO to cover the pool creation if I could get an address (feel free to dm me TG @jeremyparish)

**Pull request closed without merging**
