### PR TITLE
Frontier - Add MOBX

### PR DESCRIPTION
**Pull request by Galadrin**
Signed-off-by: David Pierret <dapie@cros-nest.com>

### CODE REVIEW

**Comment by Galadrin** [comment]
depends on https://github.com/cosmos/chain-registry/pull/273

**Comment by JeremyParish69** [comment]
Can we add the mobx token logo images to this repo?

**Comment by sunnya97** [comment]
@JeremyParish69 is this PR good to go?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 is this PR good to go?

I believe Imperator doesn't want tokens being added before there's liquidity; plus, MOBX isn't even on Frontier yet.

**Comment by Galadrin** [comment]
yes, only incentivized token are traked on the imperator API.

I'm waiting for MOBIX team to continue integration.

**Comment by sunnya97** [comment]
But isn't this just adding to frontier assetlist?

**Comment by JeremyParish69** [comment]
Although tokens don't need to be incentivized to be tracked by Imperator API, they do want there to be liquidity of it on Osmosis before signaling to them to add more assets; this is why I was holding off adding here (which signals to Imperator to add it to the Frontier Info site) until there has been liquidity added on Osmosis.

**Comment by JeremyParish69** [comment]
Closing due to inactivity

**Pull request closed without merging**
