### PR TITLE
QWOYN

### PR DESCRIPTION
**Pull request by sunnya97**
### Adding Chains

If adding a new chain, please ensure the following:
- [ ] Chain is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).

  Note:
   - Chain's registration must have `staking` defined, with at least one `staking_token` denom specified.
   - Chain's registration must have `fees` defined; at least one fee token has low, average, and high gas prices defined.
- [ ] Add chain to bottom of `zone_chains.json`

  Note:
   - RPC and REST must not have any CORS blocking of the Osmosis domain.
   - RCP node must have WSS enabled.

### Adding Assets

If adding a new asset, please ensure the following:
- [ ] Asset is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
- [ ] Add asset to bottom of `zone_assets.json`.

  Note:
   - The IBC channel referenced in `path` must be registered to the Chain Registry.
   - `osmosis_main` defaults to `false` (or else cite the listing rule that justifies enlisting to the Main app)

### On-chain liquidity

If adding a new asset, please provide the plan for on-chain liquidity of the asset: (choose one)
- [ ] The submitting team will ensure a pool will be created soon. Please hold off until further communication, which will notify of the Pool ID. (Please set the PR's status to Draft until the pool has been created)

OR
- [ ] A preview link is requested for the submitting team to be able to create a pool using the Osmosis Frontend.

OR
- [ ] The token is, or will be, going through a StreamSwap stream; thus, the token should be listed without requiring on-chain liquidity. A Pool ID will be provided in this PR following the stream's completion once the team has had a chance to create a pool using the earned funds.

### Validation Testing

If adding or updating a chain or asset, the changes must be validated from the updated build of the Osmosis Frontend. Testers will need a small amount of tokens to validate. 
  - [ ] Validaters can buy a small amount of this asset from Pool ID: {PROVIDE POOL ID}.
  - [ ] Preview build has been validated.

### CODE REVIEW

**Comment by dpdanpittman** [comment]
Thanks @sunnya97

**Comment by dpdanpittman** [comment]
@JeremyParish69 I'm not sure I did this properly.  I was confused about the stableswap yet decided to do it regardless.  No there are 50 QWOYN and 174 axl.USDC in the pool.  When I go to swap, I'm seeing 1.39 USDC per QWOYN.  When I got to add liquidity it wants me to add 3.49 USDC per 1 QWOYN.  Maybe its just not properly working yet :man_shrugging:

Can you give me some insight into this?

**Comment by JeremyParish69** [comment]
> @JeremyParish69 I'm not sure I did this properly. I was confused about the stableswap yet decided to do it regardless. Now there are 50 QWOYN and 174 axl.USDC in the pool. When I go to swap, I'm seeing 1.39 USDC per QWOYN. When I go to add liquidity it wants me to add 3.49 USDC per 1 QWOYN. Maybe its just not properly working yet 🤷‍♂️
> 
> Can you give me some insight into this?

It sounds like Stableswap is working exactly as intended. It sacrifices liquidity balance for keeping a more balanced spot price. It is expected that adding liquidity asks for asymmetrical amounts of liquidity, because that's precisely what stableswap allows to change a lot. If you can balance it closer to where the scaling factor is set, the amounts of each token require when adding liquidity will be more balanced.

**Comment by JeremyParish69** [comment]
Also, looks like the low fee rate registered for QWOYN is below the chain minimum, so this is failing validation on Osmosis frontend:
`transaction failed with code 13 (codespace: ). Log: insufficient fees; got: 1103uqwoyn required: 2757uqwoyn: insufficient fee`

**Comment by dpdanpittman** [comment]
Damn yeah, I think I chose the wrong pool type.  As far as the fee rate, do you mean on the cosmos chain registry?  I will create a new weighted pool now that I know I did it wrong.  Sorry about the trouble.

**Comment by dpdanpittman** [comment]
@JeremyParish69 ok new pool is 1295

**Comment by JeremyParish69** [comment]
> Damn yeah, I think I chose the wrong pool type. As far as the fee rate, do you mean on the cosmos chain registry? I will create a new weighted pool now that I know I did it wrong. Sorry about the trouble.

Yes, for the Gas prices, we actually require that the Chain Registry has low, average, and high gas rates defined.
https://github.com/cosmos/chain-registry/blob/cb187a9c5abe2980361605837bd44fae8ca2cfe0/qwoyn/chain.json#L20

**Comment by dpdanpittman** [comment]
Will make a PR in a bit for that. Thanks for the heads up

**Comment by dpdanpittman** [comment]
@JeremyParish69 all set, thanks again for all your help.

**Pull request merged**
