### PR TITLE
Adding chain: Scorum

### PR DESCRIPTION
**Pull request by mikluke**
## Description

Adding chain: Scorum

### Adding Chains

If adding a new chain, please ensure the following:
- [x] Chain is registered to the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - Chain's registration must have `staking` defined, with at least one `staking_token` denom specified.
   - Chain's registration must have `fees` defined; at least one fee token has low, average, and high gas prices defined.
- [x] Add chain to bottom of `zone_chains.json`
   - RPC and REST must not have any CORS blocking of the Osmosis domain.
   - RCP node must have WSS enabled.

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Since there is no pool, do you request a preview of the frontend to create one?
Please resolve conflicts.

**Comment by mikluke** [comment]
Conflicts resolved
> Since there is no pool, do you request a preview of the frontend to create one?
Yes, as soon the pr gets accepted we'll create a pool

**Comment by JeremyParish69** [comment]
The validation failed because there is no IBC connection between scorum and osmosis registered to the Chain Registry. Please register it there https://github.com/cosmos/chain-registry/tree/master/_IBC

**Comment by JeremyParish69** [comment]
You will be able to create classic (kxy) pools using the preview frontend here: https://app.osmosis.zone/assets?show_unlisted_assets=true
This will not allow you to create Supercharged (CL) pools, as that can only be done via CLI.
Please let us know once there is there is liquidity to proceed with the validation process.

**Pull request merged**
