### PR TITLE
Harbor asset added

### PR DESCRIPTION
**Pull request by Subham2804**

### CODE REVIEW

**Comment by JeremyParish69** [comment]
Thanks. Is there a pool id for this yet?

**Comment by Subham2804** [comment]
No , there isn't any pool yet

**Comment by JeremyParish69** [comment]
> No , there isn't any pool yet

Is a staging link required to create one?

**Comment by Subham2804** [comment]
will be doing Harbor incentives on pools

**Comment by Subham2804** [comment]
> 

can you please provide staging link

**Comment by Subham2804** [comment]
added pool_id : 947

**Comment by JeremyParish69** [comment]
@Subham2804 Could you please validate deposit and withdrawal via the staging link?
https://osmosis-frontier-git-jp69-add-harbor-osmo-labs.vercel.app/

**Comment by Subham2804** [comment]
Tested , working fine

**Pull request closed without merging**
