### PR TITLE
Make PURSE Verified

### PR DESCRIPTION
**Pull request by JeremyParish69**
## Description

Make PundiX PURSE Verified

### Upgrading Asset to Verified

If upgrading an Asset to Verified, please see the requirements specified at [LISTING](https://github.com/osmosis-labs/assetlists/blob/main/LISTING.md#upgrade-asset-to-verified-status-permissioned), and ensure the following:
- [x] Asset is defined thoroughly at the [Cosmos Chain Registry](https://github.com/cosmos/chain-registry).
   - [x] A meaningful `description` and `extended_description`.
   - [x] Associated `socials`, including `website` and `twitter`.
   - [x] Logo Image has a square Aspect Ratio and < 250 KB file size.
- [ ] This pool contains contains at least $1k USD-worth of liquidity of the asset (Provide Pool ID): ______

'Verified' Status Validation Checklist (to be completed by Osmosis Zone maintainers):
- [x] Verify appearance and metadata
- [x] Accurate Price
- [x] Trading and routing functionality
- [ ] Withdraw and Deposit
   - [ ] Deposit Transaction URL (if in-app)

### CODE REVIEW

**Comment by zakir-code** [comment]
Hi @JeremyParish69, We added liquidity.
https://app.osmosis.zone/pool/1695

**Comment by JeremyParish69** [comment]
> Hi @JeremyParish69, We added liquidity. https://app.osmosis.zone/pool/1695

Thanks, I was already able to Withdraw some PURSE, but the main issue is that there is no liquidity of PUNDIX, so I cannot Deposit PURSE to Osmosis.

**Comment by zakir-code** [comment]
Ok, I'll report back to my team.

**Comment by JeremyParish69** [comment]
> Ok, I'll report back to my team.

Hi, any further info on getting PUNDIX added? We cannot proceed without any PUNDIX availability.

**Comment by zakir-code** [comment]
Hi, we are very sorry, but the project needs to make some adjustments. Thank you for your support.

**Pull request closed without merging**
